/* Flashcards for key formulas and reactions.
   Each card: id, c (course key), w (week), f (front prompt), b (back), n (optional note).
   In the back text, ";  " (semicolon + two spaces) starts a new line. */
(function (root) {
  "use strict";
  root.FLASHCARDS = [

    /* ---------------- CHEM*1050 ---------------- */
    { id: "fc-c1050-01", c: "c1050", w: 1, f: "Heat absorbed or released (calorimetry)", b: "q = m·c·ΔT", n: "c(water) = 4.184 J/g·°C. q > 0 means heat is absorbed." },
    { id: "fc-c1050-02", c: "c1050", w: 1, f: "First law of thermodynamics", b: "ΔU = q + w", n: "For expansion against constant pressure, w = −PΔV." },
    { id: "fc-c1050-03", c: "c1050", w: 1, f: "Enthalpy of reaction from enthalpies of formation", b: "ΔH°rxn = Σ n·ΔH°f(products) − Σ n·ΔH°f(reactants)", n: "ΔH°f of an element in its standard state is 0." },
    { id: "fc-c1050-04", c: "c1050", w: 1, f: "Hess’s law: what happens to ΔH when you reverse or multiply a reaction?", b: "Reverse the reaction → change the sign of ΔH;  Multiply the reaction by n → multiply ΔH by n;  Add reactions → add their ΔH values" },
    { id: "fc-c1050-05", c: "c1050", w: 2, f: "Boltzmann equation for entropy", b: "S = k ln W", n: "k = 1.38 × 10⁻²³ J/K; W is the number of microstates." },
    { id: "fc-c1050-06", c: "c1050", w: 2, f: "Standard entropy change of a reaction", b: "ΔS° = Σ n·S°(products) − Σ n·S°(reactants)" },
    { id: "fc-c1050-07", c: "c1050", w: 3, f: "Second law: entropy of the universe", b: "ΔS(univ) = ΔS(sys) + ΔS(surr) > 0 (spontaneous);  ΔS(surr) = −ΔH(sys)/T" },
    { id: "fc-c1050-08", c: "c1050", w: 3, f: "Gibbs free energy", b: "ΔG = ΔH − TΔS", n: "ΔG < 0 is spontaneous. The crossover temperature is T = ΔH/ΔS." },
    { id: "fc-c1050-09", c: "c1050", w: 4, f: "Standard free energy and the equilibrium constant", b: "ΔG° = −RT ln K", n: "R = 8.314 J/mol·K. K > 1 when ΔG° < 0." },
    { id: "fc-c1050-10", c: "c1050", w: 4, f: "Free energy under non-standard conditions", b: "ΔG = ΔG° + RT ln Q", n: "Q < K: reaction goes forward. At equilibrium ΔG = 0 and Q = K." },
    { id: "fc-c1050-11", c: "c1050", w: 5, f: "Rate of reaction for aA → cC", b: "rate = −(1/a)·Δ[A]/Δt = (1/c)·Δ[C]/Δt" },
    { id: "fc-c1050-12", c: "c1050", w: 6, f: "General rate law", b: "rate = k[A]ᵐ[B]ⁿ", n: "The orders m and n come from experiment; the overall order is m + n." },
    { id: "fc-c1050-13", c: "c1050", w: 7, f: "Zero-order integrated rate law and half-life", b: "[A] = [A]₀ − kt;  t½ = [A]₀ / 2k" },
    { id: "fc-c1050-14", c: "c1050", w: 7, f: "First-order integrated rate law and half-life", b: "ln[A] = ln[A]₀ − kt;  t½ = 0.693 / k", n: "The half-life doesn’t depend on concentration." },
    { id: "fc-c1050-15", c: "c1050", w: 7, f: "Second-order integrated rate law and half-life", b: "1/[A] = 1/[A]₀ + kt;  t½ = 1 / (k[A]₀)" },
    { id: "fc-c1050-16", c: "c1050", w: 8, f: "Arrhenius equation", b: "k = A·e^(−Ea/RT)", n: "A is the frequency factor; a plot of ln k vs 1/T has slope −Ea/R." },
    { id: "fc-c1050-17", c: "c1050", w: 8, f: "Arrhenius equation for two temperatures", b: "ln(k₂/k₁) = (Ea/R)·(1/T₁ − 1/T₂)" },
    { id: "fc-c1050-18", c: "c1050", w: 9, f: "Oxidation and reduction", b: "Oxidation Is Loss of electrons (oxidation number rises);  Reduction Is Gain of electrons (oxidation number falls)", n: "The oxidizing agent is reduced; the reducing agent is oxidized. Oxidation happens at the anode." },
    { id: "fc-c1050-19", c: "c1050", w: 10, f: "Standard cell potential", b: "E°cell = E°(cathode) − E°(anode)", n: "Use standard reduction potentials for both." },
    { id: "fc-c1050-20", c: "c1050", w: 10, f: "Cell potential, free energy and K", b: "ΔG° = −nFE°cell;  E°cell = (0.0592 V / n)·log K at 298 K", n: "F = 96,485 C/mol of electrons." },
    { id: "fc-c1050-21", c: "c1050", w: 10, f: "Nernst equation at 298 K", b: "E = E° − (0.0592 V / n)·log Q" },
    { id: "fc-c1050-22", c: "c1050", w: 11, f: "Faraday’s law of electrolysis", b: "charge Q = I·t;  moles of e⁻ = I·t / F", n: "Then use the half-reaction’s mole ratio, e.g. Cu²⁺ + 2e⁻ → Cu." },

    /* ---------------- CHEM*2700 ---------------- */
    { id: "fc-c2700-01", c: "c2700", w: 1, f: "pKa and acid strength", b: "pKa = −log Ka", n: "Lower pKa = stronger acid. An acid–base equilibrium favours the weaker acid (higher pKa)." },
    { id: "fc-c2700-02", c: "c2700", w: 1, f: "Formal charge", b: "FC = valence e⁻ − nonbonding e⁻ − ½(bonding e⁻)" },
    { id: "fc-c2700-03", c: "c2700", w: 2, f: "Substituted cyclohexanes: which arrangements are axial or equatorial?", b: "Large groups prefer equatorial;  cis-1,2 and trans-1,3: one axial, one equatorial;  trans-1,2 and cis-1,3: both can be equatorial" },
    { id: "fc-c2700-04", c: "c2700", w: 3, f: "Assigning R or S (Cahn–Ingold–Prelog)", b: "Rank groups by atomic number;  Point the lowest priority away from you;  1 → 2 → 3 clockwise = R, counterclockwise = S", n: "If the lowest priority points toward you, reverse your answer." },
    { id: "fc-c2700-05", c: "c2700", w: 3, f: "Maximum number of stereoisomers", b: "2ⁿ for n stereocentres", n: "Fewer if meso compounds exist." },
    { id: "fc-c2700-06", c: "c2700", w: 4, f: "Curved-arrow rules", b: "Arrows start at electrons (lone pair or bond);  Arrows end at an atom or a new bond position;  Nucleophile → electrophile;  No second-row atom may exceed an octet" },
    { id: "fc-c2700-07", c: "c2700", w: 5, f: "SN2 reaction", b: "Nu⁻ + R–X → Nu–R + X⁻;  rate = k[RX][Nu⁻]", n: "One step, backside attack, inversion. Methyl > 1° > 2° (not 3°). Favoured by polar aprotic solvents." },
    { id: "fc-c2700-08", c: "c2700", w: 5, f: "SN1 reaction", b: "R–X → R⁺ + X⁻ (slow);  R⁺ + Nu → R–Nu (fast);  rate = k[RX]", n: "Carbocation intermediate: racemization and possible rearrangement. 3° > 2°. Favoured by polar protic solvents." },
    { id: "fc-c2700-09", c: "c2700", w: 6, f: "E2 reaction", b: "B⁻ + H–C–C–X → C=C + B–H + X⁻;  rate = k[RX][B⁻]", n: "One step; H and X must be anti-periplanar. Gives the Zaitsev (more substituted) alkene unless the base is bulky." },
    { id: "fc-c2700-10", c: "c2700", w: 6, f: "E1 reaction", b: "R–X → R⁺ + X⁻ (slow);  loss of a β-H → alkene;  rate = k[RX]", n: "Competes with SN1 and is favoured by heat. Gives the Zaitsev alkene." },
    { id: "fc-c2700-11", c: "c2700", w: 7, f: "Degree of unsaturation", b: "DoU = (2C + 2 + N − H − X) / 2", n: "Each ring or π bond counts as 1." },
    { id: "fc-c2700-12", c: "c2700", w: 7, f: "Alkene + HX (HCl, HBr)", b: "C=C + HX → H–C–C–X", n: "Markovnikov: H adds to the carbon with more H’s, X to the more substituted carbon. Goes through a carbocation, so rearrangements are possible." },
    { id: "fc-c2700-13", c: "c2700", w: 8, f: "Alkene + Br₂ (or Cl₂)", b: "C=C + Br₂ → vicinal dibromide", n: "Through a bromonium ion, so anti addition." },
    { id: "fc-c2700-14", c: "c2700", w: 8, f: "Halohydrin formation", b: "C=C + Br₂, H₂O → bromohydrin", n: "OH goes on the more substituted carbon; anti addition." },
    { id: "fc-c2700-15", c: "c2700", w: 8, f: "Oxymercuration–demercuration", b: "C=C + 1. Hg(OAc)₂, H₂O  2. NaBH₄ → alcohol", n: "Markovnikov OH, with no rearrangement." },
    { id: "fc-c2700-16", c: "c2700", w: 8, f: "Hydroboration–oxidation", b: "C=C + 1. BH₃, THF  2. H₂O₂, NaOH → alcohol", n: "Anti-Markovnikov OH; H and OH add syn." },
    { id: "fc-c2700-17", c: "c2700", w: 8, f: "Catalytic hydrogenation of an alkene", b: "C=C + H₂, Pd/C → alkane", n: "Syn addition." },
    { id: "fc-c2700-18", c: "c2700", w: 8, f: "Epoxidation and dihydroxylation", b: "C=C + RCO₃H (mCPBA) → epoxide;  C=C + 1. OsO₄  2. NaHSO₃, H₂O → cis-1,2-diol", n: "Both add syn." },
    { id: "fc-c2700-19", c: "c2700", w: 8, f: "Ozonolysis", b: "C=C + 1. O₃  2. Zn, H₃O⁺ → two carbonyl compounds", n: "Each carbon of the double bond becomes a C=O." },
    { id: "fc-c2700-20", c: "c2700", w: 9, f: "Radical halogenation of an alkane", b: "R–H + X₂, light (hν) → R–X + HX", n: "Chain reaction: initiation, propagation, termination. Br₂ is highly selective for tertiary C–H." },
    { id: "fc-c2700-21", c: "c2700", w: 9, f: "Allylic bromination", b: "Alkene + NBS, light (hν) → allylic bromide", n: "Goes through a resonance-stabilized allylic radical." },
    { id: "fc-c2700-22", c: "c2700", w: 10, f: "Hückel’s rule for aromaticity", b: "Cyclic, planar, fully conjugated;  4n + 2 π electrons (2, 6, 10 …)", n: "4n π electrons in such a ring is antiaromatic." },
    { id: "fc-c2700-23", c: "c2700", w: 10, f: "EAS: bromination and nitration of benzene", b: "ArH + Br₂, FeBr₃ → ArBr + HBr;  ArH + HNO₃, H₂SO₄ → ArNO₂ + H₂O", n: "The electrophiles are Br⁺ (activated by FeBr₃) and NO₂⁺." },
    { id: "fc-c2700-24", c: "c2700", w: 10, f: "EAS: Friedel–Crafts alkylation and acylation", b: "ArH + RCl, AlCl₃ → ArR;  ArH + RCOCl, AlCl₃ → ArCOR", n: "Alkylation can rearrange and over-alkylate. Neither works on strongly deactivated rings such as nitrobenzene." },
    { id: "fc-c2700-25", c: "c2700", w: 10, f: "Substituent effects in EAS", b: "Activating, ortho/para: –OH, –OR, –NH₂, –R;  Deactivating, ortho/para: –F, –Cl, –Br, –I;  Deactivating, meta: –NO₂, –CN, –SO₃H, –CHO, –COR, –COOH, –CO₂R" },
    { id: "fc-c2700-26", c: "c2700", w: 11, f: "Aldehyde or ketone + hydride or Grignard reagent", b: "R₂C=O + 1. NaBH₄  2. H₃O⁺ → alcohol;  R₂C=O + 1. R′MgBr  2. H₃O⁺ → alcohol with a new C–C bond", n: "Grignard: formaldehyde → 1°, other aldehydes → 2°, ketones → 3° alcohols." },
    { id: "fc-c2700-27", c: "c2700", w: 11, f: "Imine and enamine formation", b: "R₂C=O + R′NH₂ ⇌ R₂C=NR′ + H₂O (imine);  R₂C=O + R′₂NH ⇌ enamine + H₂O", n: "Acid-catalyzed; fastest around pH 4–5." },
    { id: "fc-c2700-28", c: "c2700", w: 11, f: "Acetal formation", b: "R₂C=O + 2 R′OH, H⁺ ⇌ R₂C(OR′)₂ + H₂O", n: "Goes through a hemiacetal. Aqueous acid reverses it, so acetals are used to protect carbonyls." },
    { id: "fc-c2700-29", c: "c2700", w: 12, f: "Nucleophilic acyl substitution (general pattern)", b: "RCOY + Nu⁻ → tetrahedral intermediate → RCONu + Y⁻", n: "Reactivity: acid chloride > anhydride > thioester > ester > amide." },
    { id: "fc-c2700-30", c: "c2700", w: 12, f: "Ester hydrolysis and Fischer esterification", b: "RCOOR′ + NaOH → RCOO⁻ Na⁺ + R′OH (saponification);  RCOOH + R′OH, H⁺ ⇌ RCOOR′ + H₂O", n: "Saponification can’t reverse; Fischer esterification is an equilibrium." },
    { id: "fc-c2700-31", c: "c2700", w: 12, f: "Reactions of acid chlorides", b: "RCOCl + R′OH → ester + HCl;  RCOCl + 2 NH₃ → amide + NH₄Cl;  RCOCl + H₂O → carboxylic acid + HCl", n: "Acid chlorides are made from RCOOH + SOCl₂." },
    { id: "fc-c2700-32", c: "c2700", w: 12, f: "Henderson–Hasselbalch for a carboxylic acid", b: "pH = pKa + log([RCOO⁻] / [RCOOH])", n: "At pH 7.4, carboxylic acids (pKa ≈ 4–5) are almost entirely carboxylate ions." },

    /* ---------------- BIOC*2580 ---------------- */
    { id: "fc-c2580-01", c: "c2580", w: 1, f: "Henderson–Hasselbalch equation", b: "pH = pKa + log([A⁻] / [HA])", n: "Buffers work best within about 1 unit of the pKa." },
    { id: "fc-c2580-02", c: "c2580", w: 1, f: "pH, pOH and Kw", b: "pH = −log[H⁺];  Kw = [H⁺][OH⁻] = 1.0 × 10⁻¹⁴ at 25 °C;  pH + pOH = 14" },
    { id: "fc-c2580-03", c: "c2580", w: 2, f: "Isoelectric point of a simple amino acid", b: "pI = (pKa₁ + pKa₂) / 2", n: "With an ionizable side chain, average the two pKa values on either side of the neutral form." },
    { id: "fc-c2580-04", c: "c2580", w: 2, f: "Peptide bond formation", b: "–COOH + H₂N– → –CO–NH– + H₂O", n: "A condensation. The peptide bond is planar, with partial double-bond character." },
    { id: "fc-c2580-05", c: "c2580", w: 3, f: "α-helix and β-sheet key numbers", b: "α-helix: 3.6 residues per turn, 0.54 nm per turn;  α-helix H-bonds: C=O of residue n to N–H of residue n + 4;  β-sheet: extended strands, H-bonds between strands" },
    { id: "fc-c2580-06", c: "c2580", w: 4, f: "Fraction of binding sites occupied (myoglobin)", b: "θ = [L] / ([L] + Kd);  θ = pO₂ / (pO₂ + P₅₀)", n: "A lower Kd or P₅₀ means higher affinity." },
    { id: "fc-c2580-07", c: "c2580", w: 4, f: "Hill equation", b: "log[θ / (1 − θ)] = n·log[L] − log Kd", n: "Hill coefficient > 1 means positive cooperativity (hemoglobin ≈ 3); = 1 means none (myoglobin)." },
    { id: "fc-c2580-08", c: "c2580", w: 5, f: "Linkages in maltose, lactose and sucrose", b: "Maltose: Glc α(1→4) Glc;  Lactose: Gal β(1→4) Glc;  Sucrose: Glc α(1↔2)β Fru", n: "Sucrose is non-reducing because both anomeric carbons are in the glycosidic bond." },
    { id: "fc-c2580-09", c: "c2580", w: 6, f: "Michaelis–Menten equation", b: "v₀ = Vmax[S] / (Km + [S])", n: "Km is the [S] at which v₀ = ½Vmax." },
    { id: "fc-c2580-10", c: "c2580", w: 6, f: "Lineweaver–Burk (double-reciprocal) equation", b: "1/v₀ = (Km / Vmax)·(1/[S]) + 1/Vmax", n: "x-intercept = −1/Km; y-intercept = 1/Vmax." },
    { id: "fc-c2580-11", c: "c2580", w: 6, f: "Turnover number and catalytic efficiency", b: "kcat = Vmax / [E]total;  efficiency = kcat / Km" },
    { id: "fc-c2580-12", c: "c2580", w: 6, f: "Effect of a competitive inhibitor", b: "apparent Km = α·Km, where α = 1 + [I]/Ki;  Vmax unchanged" },
    { id: "fc-c2580-13", c: "c2580", w: 7, f: "Serine protease (chymotrypsin) mechanism in brief", b: "Ser195 attacks the peptide C=O, with His57 as base;  Tetrahedral intermediate is held in the oxyanion hole;  Amine half leaves → acyl-enzyme;  Water attacks → acid half released", n: "Catalytic triad: Ser195, His57, Asp102." },
    { id: "fc-c2580-14", c: "c2580", w: 8, f: "Base pairing and Chargaff’s rules", b: "A–T: 2 hydrogen bonds;  G–C: 3 hydrogen bonds;  %A = %T and %G = %C;  Strands are antiparallel (5′→3′ against 3′→5′)" },
    { id: "fc-c2580-15", c: "c2580", w: 9, f: "Free energy of moving a solute across a membrane", b: "ΔG = RT ln(C₂/C₁) + ZFΔψ", n: "For an uncharged solute the second term is zero. ΔG < 0 means the move can happen passively." },
    { id: "fc-c2580-16", c: "c2580", w: 10, f: "Free energy of coupled reactions", b: "ΔG°′(total) = ΔG°′₁ + ΔG°′₂", n: "ATP → ADP + Pi has ΔG°′ = −30.5 kJ/mol." },
    { id: "fc-c2580-17", c: "c2580", w: 10, f: "Actual free-energy change in the cell", b: "ΔG = ΔG°′ + RT ln([products] / [reactants])" },
    { id: "fc-c2580-18", c: "c2580", w: 10, f: "Glycolysis: overall equation", b: "Glucose + 2 NAD⁺ + 2 ADP + 2 Pi → 2 pyruvate + 2 NADH + 2 H⁺ + 2 ATP + 2 H₂O" },
    { id: "fc-c2580-19", c: "c2580", w: 10, f: "The three irreversible steps of glycolysis", b: "Hexokinase: glucose → glucose 6-phosphate;  PFK-1: fructose 6-phosphate → fructose 1,6-bisphosphate;  Pyruvate kinase: phosphoenolpyruvate → pyruvate", n: "PFK-1 is the main control point." },
    { id: "fc-c2580-20", c: "c2580", w: 10, f: "Lactate fermentation", b: "Pyruvate + NADH + H⁺ → lactate + NAD⁺", n: "Lactate dehydrogenase regenerates NAD⁺ so glycolysis can continue without O₂." },
    { id: "fc-c2580-21", c: "c2580", w: 11, f: "Pyruvate dehydrogenase complex", b: "Pyruvate + CoA + NAD⁺ → acetyl-CoA + CO₂ + NADH", n: "Cofactors: TPP, lipoate, CoA, FAD, NAD⁺." },
    { id: "fc-c2580-22", c: "c2580", w: 11, f: "Citric acid cycle: products per acetyl-CoA", b: "2 CO₂;  3 NADH;  1 FADH₂;  1 GTP (or ATP)" },
    { id: "fc-c2580-23", c: "c2580", w: 11, f: "Citric acid cycle: order of intermediates", b: "Citrate → isocitrate → α-ketoglutarate → succinyl-CoA;  → succinate → fumarate → malate → oxaloacetate;  Oxaloacetate + acetyl-CoA → citrate", n: "Memory aid: Citrate Is Krebs’ Starting Substrate For Making Oxaloacetate." },
    { id: "fc-c2580-24", c: "c2580", w: 12, f: "Redox potential and free energy", b: "ΔG°′ = −nFΔE°′;  ΔE°′ = E°′(electron acceptor) − E°′(electron donor)" },
    { id: "fc-c2580-25", c: "c2580", w: 12, f: "Electron transport chain order", b: "NADH → Complex I → Q;  Succinate → Complex II → Q;  Q → Complex III → cytochrome c → Complex IV → O₂" },
    { id: "fc-c2580-26", c: "c2580", w: 12, f: "ATP yields from oxidative phosphorylation", b: "≈ 2.5 ATP per NADH;  ≈ 1.5 ATP per FADH₂;  ≈ 30–32 ATP per glucose" },
    { id: "fc-c2580-27", c: "c2580", w: 12, f: "One round of β-oxidation", b: "Fatty acyl-CoA (n carbons) → fatty acyl-CoA (n − 2) + acetyl-CoA + FADH₂ + NADH", n: "Palmitoyl-CoA (16 C) takes 7 rounds and gives 8 acetyl-CoA." },

    /* ---------------- IPS*1500 ---------------- */
    { id: "fc-c1500-01", c: "c1500", w: 1, f: "Vector components, magnitude and direction", b: "Aₓ = A cos θ;  A_y = A sin θ;  |A| = √(Aₓ² + A_y²);  θ = tan⁻¹(A_y / Aₓ)" },
    { id: "fc-c1500-02", c: "c1500", w: 1, f: "Dot and cross products", b: "A·B = AB cos θ = AₓBₓ + A_yB_y + A_zB_z;  |A × B| = AB sin θ", n: "The cross product is perpendicular to both vectors (right-hand rule)." },
    { id: "fc-c1500-03", c: "c1500", w: 1, f: "Core trig identities", b: "sin²θ + cos²θ = 1;  sin 2θ = 2 sin θ cos θ;  cos 2θ = cos²θ − sin²θ" },
    { id: "fc-c1500-04", c: "c1500", w: 2, f: "Two standard trig limits", b: "lim(x→0) sin x / x = 1;  lim(x→0) (1 − cos x) / x = 0" },
    { id: "fc-c1500-05", c: "c1500", w: 3, f: "Definition of the derivative", b: "f′(x) = lim(h→0) [f(x + h) − f(x)] / h" },
    { id: "fc-c1500-06", c: "c1500", w: 3, f: "Velocity and acceleration as derivatives", b: "v = dx/dt;  a = dv/dt = d²x/dt²" },
    { id: "fc-c1500-07", c: "c1500", w: 3, f: "Constant-acceleration equations", b: "v = v₀ + at;  x = x₀ + v₀t + ½at²;  v² = v₀² + 2a(x − x₀)", n: "Free fall: a = −g = −9.8 m/s² (taking up as positive)." },
    { id: "fc-c1500-08", c: "c1500", w: 4, f: "Power, product and quotient rules", b: "d/dx xⁿ = n·xⁿ⁻¹;  (fg)′ = f′g + fg′;  (f/g)′ = (f′g − fg′) / g²" },
    { id: "fc-c1500-09", c: "c1500", w: 4, f: "Chain rule", b: "d/dx f(g(x)) = f′(g(x))·g′(x)" },
    { id: "fc-c1500-10", c: "c1500", w: 4, f: "Derivatives of trig, exponential and log functions", b: "(sin x)′ = cos x;  (cos x)′ = −sin x;  (tan x)′ = sec²x;  (eˣ)′ = eˣ;  (ln x)′ = 1/x" },
    { id: "fc-c1500-11", c: "c1500", w: 5, f: "Projectile on level ground (launch speed v₀, angle θ)", b: "Time of flight T = 2v₀ sin θ / g;  Maximum height H = (v₀ sin θ)² / 2g;  Range R = v₀² sin 2θ / g" },
    { id: "fc-c1500-12", c: "c1500", w: 5, f: "Centripetal acceleration", b: "a_c = v² / r = ω²r", n: "Points toward the centre of the circle." },
    { id: "fc-c1500-13", c: "c1500", w: 6, f: "Newton’s second law", b: "ΣF = ma", n: "Weight w = mg. Draw a free-body diagram first." },
    { id: "fc-c1500-14", c: "c1500", w: 7, f: "Friction", b: "Static: f_s ≤ μs·N;  Kinetic: f_k = μk·N", n: "On an incline with no push, the block stays put if μs ≥ tan θ." },
    { id: "fc-c1500-15", c: "c1500", w: 7, f: "Basic antiderivatives", b: "∫xⁿ dx = xⁿ⁺¹ / (n + 1) + C  (n ≠ −1);  ∫(1/x) dx = ln|x| + C;  ∫cos x dx = sin x + C;  ∫eˣ dx = eˣ + C" },
    { id: "fc-c1500-16", c: "c1500", w: 8, f: "Fundamental Theorem of Calculus", b: "d/dx ∫ₐˣ f(t) dt = f(x);  ∫ₐᵇ f(x) dx = F(b) − F(a), where F′ = f" },
    { id: "fc-c1500-17", c: "c1500", w: 9, f: "Work", b: "Constant force: W = Fd cos θ;  Variable force: W = ∫F(x) dx", n: "Spring: W = ½kx² to stretch from 0 to x." },
    { id: "fc-c1500-18", c: "c1500", w: 9, f: "Kinetic and potential energy", b: "KE = ½mv²;  Gravitational U = mgh;  Spring U = ½kx²" },
    { id: "fc-c1500-19", c: "c1500", w: 9, f: "Work–energy theorem, energy conservation and power", b: "W_net = ΔKE;  KE₁ + U₁ = KE₂ + U₂ (no friction);  P = W / t = Fv" },
    { id: "fc-c1500-20", c: "c1500", w: 10, f: "Momentum and impulse", b: "p = mv;  J = Δp = F_avg·Δt" },
    { id: "fc-c1500-21", c: "c1500", w: 10, f: "Conservation of momentum and centre of mass", b: "Σp(before) = Σp(after) when no external force acts;  x_cm = Σmᵢxᵢ / Σmᵢ", n: "Elastic collisions also conserve KE; in perfectly inelastic collisions the objects stick together." },
    { id: "fc-c1500-22", c: "c1500", w: 11, f: "Rotational kinematics", b: "ω = ω₀ + αt;  θ = ω₀t + ½αt²;  v = rω;  a_t = rα" },
    { id: "fc-c1500-23", c: "c1500", w: 11, f: "Torque, rotational second law and rotational KE", b: "τ = rF sin θ;  Στ = Iα;  KE_rot = ½Iω²", n: "I: solid disk ½MR², hoop MR², solid sphere ⅖MR², rod about its centre (1/12)ML²." },
    { id: "fc-c1500-24", c: "c1500", w: 11, f: "Angular momentum", b: "L = Iω;  L is conserved when the net external torque is zero" },
    { id: "fc-c1500-25", c: "c1500", w: 12, f: "Lorentz factor, time dilation and length contraction", b: "γ = 1 / √(1 − v²/c²);  Δt = γ·Δt₀;  L = L₀ / γ", n: "Δt₀ and L₀ are measured in the object’s own rest frame." },
    { id: "fc-c1500-26", c: "c1500", w: 12, f: "Relativistic energy and momentum", b: "Rest energy E₀ = mc²;  Total energy E = γmc²;  p = γmv;  E² = (pc)² + (mc²)²" },
    { id: "fc-c1500-27", c: "c1500", w: 12, f: "Hydrogen atom energy levels", b: "Eₙ = −13.6 eV / n²", n: "Photon from a transition: E = hf = E(initial) − E(final)." }
  ];
})(typeof self !== "undefined" ? self : this);
