/* Practice midterms, one per course, covering weeks 1–6.
   Multiple choice: { t: "mc", w, q, o: [4 options], a: index of correct option, e: explanation }
   Written:         { t: "sa", w, q, s: model answer (";  " starts a new line), r: [[rubric point, marks], ...] } */
(function (root) {
  "use strict";
  root.PRACTICE_EXAMS = {

    /* ---------------- CHEM*1050 ---------------- */
    c1050: {
      weeks: [1, 6],
      minutes: 50,
      covers: "Thermochemistry and Hess’s law, entropy, the second and third laws, Gibbs free energy, free energy and equilibrium, reaction rates and rate laws (Chemistry 2e Ch. 5, 12.1–12.3, 13.1–13.3, 16). Use R = 8.314 J/mol·K.",
      questions: [
        { t: "mc", w: 1, q: "A 50.0 g piece of metal releases 1.20 kJ of heat as it cools from 100.0 °C to 25.0 °C. What is its specific heat?",
          o: ["0.240 J/g·°C", "0.320 J/g·°C", "0.480 J/g·°C", "3.20 J/g·°C"], a: 1,
          e: "c = q/(mΔT) = 1200 J ÷ (50.0 g × 75.0 °C) = 0.320 J/g·°C." },
        { t: "mc", w: 1, q: "ΔH°f (kJ/mol): CO₂(g) −393.5, H₂O(l) −285.8, CH₄(g) −74.8. What is ΔH° for CH₄(g) + 2 O₂(g) → CO₂(g) + 2 H₂O(l)?",
          o: ["−604.5 kJ", "+890.3 kJ", "−965.1 kJ", "−890.3 kJ"], a: 3,
          e: "ΔH° = [−393.5 + 2(−285.8)] − [−74.8 + 0] = −890.3 kJ. −604.5 forgets the 2 for water; −965.1 forgets to subtract methane." },
        { t: "mc", w: 1, q: "Which of these is a state function?",
          o: ["Heat, q", "Work, w", "Enthalpy, H", "Both heat and work"], a: 2,
          e: "Enthalpy depends only on the initial and final states. Heat and work depend on the path taken." },
        { t: "mc", w: 2, q: "Which process has a negative entropy change?",
          o: ["2 H₂(g) + O₂(g) → 2 H₂O(l)", "H₂O(l) → H₂O(g)", "CaCO₃(s) → CaO(s) + CO₂(g)", "NH₄NO₃(s) dissolving in water"], a: 0,
          e: "Three moles of gas become liquid water, a large loss of microstates. The other three all increase disorder." },
        { t: "mc", w: 2, q: "For which reaction is ΔS° closest to zero?",
          o: ["N₂O₄(g) → 2 NO₂(g)", "H₂(g) + Cl₂(g) → 2 HCl(g)", "2 SO₂(g) + O₂(g) → 2 SO₃(g)", "CaO(s) + CO₂(g) → CaCO₃(s)"], a: 1,
          e: "Two moles of gas become two moles of gas, so the entropy barely changes. The others change the number of moles of gas." },
        { t: "mc", w: 3, q: "A reaction has ΔH = +40 kJ and ΔS = +120 J/K. When is it spontaneous?",
          o: ["At all temperatures", "At no temperature", "Only above about 333 K", "Only below about 333 K"], a: 2,
          e: "With ΔH and ΔS both positive, ΔG becomes negative when T > ΔH/ΔS = 40,000 J ÷ 120 J/K ≈ 333 K." },
        { t: "mc", w: 3, q: "A process at 298 K has ΔH(sys) = −59.6 kJ. What is ΔS(surr)?",
          o: ["−200 J/K", "+200 J/K", "+0.200 J/K", "−17.8 J/K"], a: 1,
          e: "ΔS(surr) = −ΔH(sys)/T = +59,600 J ÷ 298 K = +200 J/K. Heat released warms the surroundings, raising their entropy." },
        { t: "mc", w: 4, q: "At 298 K a reaction has K = 1. What is ΔG°?",
          o: ["ΔG° = 0", "ΔG° > 0", "ΔG° < 0", "ΔG° = −RT"], a: 0,
          e: "ΔG° = −RT ln K and ln 1 = 0." },
        { t: "mc", w: 4, q: "A reaction has ΔG° = +5.0 kJ/mol at 298 K. The reaction quotient is Q = 1.0 × 10⁻³. Which statement is true?",
          o: ["ΔG = +5.0 kJ/mol, so the reaction runs in reverse", "ΔG ≈ +22 kJ/mol, so the reaction runs in reverse", "The system is at equilibrium", "ΔG ≈ −12 kJ/mol, so the reaction runs forward"], a: 3,
          e: "ΔG = ΔG° + RT ln Q = 5000 + (8.314)(298)(ln 1.0 × 10⁻³) = 5000 − 17,100 ≈ −12 kJ/mol. Negative, so it proceeds forward." },
        { t: "mc", w: 5, q: "For N₂(g) + 3 H₂(g) → 2 NH₃(g), NH₃ forms at 0.060 M/s. How fast is H₂ used up?",
          o: ["0.020 M/s", "0.040 M/s", "0.090 M/s", "0.12 M/s"], a: 2,
          e: "H₂ is used 3/2 as fast as NH₃ forms: (3/2)(0.060) = 0.090 M/s." },
        { t: "mc", w: 6, q: "Rate = k[A]²[B]. If [A] is halved and [B] is doubled, the rate…",
          o: ["doubles", "is halved", "stays the same", "falls to one quarter"], a: 1,
          e: "(½)² × 2 = ½, so the rate is halved." },
        { t: "mc", w: 6, q: "Rate = k[A], with rate in M/s. What are the units of k?",
          o: ["M s⁻¹", "M⁻¹ s⁻¹", "M⁻² s⁻¹", "s⁻¹"], a: 3,
          e: "k = rate/[A] = (M/s)/M = s⁻¹, the unit for any first-order rate constant." },
        { t: "sa", w: 1, q: "Given: (1) N₂(g) + O₂(g) → 2 NO(g), ΔH = +180.6 kJ; (2) N₂(g) + 2 O₂(g) → 2 NO₂(g), ΔH = +66.4 kJ. Find ΔH for 2 NO(g) + O₂(g) → 2 NO₂(g). Show how you combined the equations, and state whether the reaction is exothermic or endothermic.",
          s: "Reverse (1): 2 NO(g) → N₂(g) + O₂(g), ΔH = −180.6 kJ;  Add (2): N₂(g) + 2 O₂(g) → 2 NO₂(g), ΔH = +66.4 kJ;  N₂ cancels and one O₂ cancels: 2 NO(g) + O₂(g) → 2 NO₂(g);  ΔH = −180.6 + 66.4 = −114.2 kJ, so the reaction is exothermic.",
          r: [["Reversed equation (1) and changed the sign of its ΔH", 1.5], ["Added equation (2) and cancelled N₂ and O₂ correctly", 1], ["ΔH = −114.2 kJ", 1], ["Stated that it is exothermic", 0.5]] },
        { t: "sa", w: 4, q: "For 2 NO₂(g) ⇌ N₂O₄(g): ΔH° = −57.2 kJ and ΔS° = −175.8 J/K. (a) Calculate ΔG° at 298 K. (b) Calculate K at 298 K. (c) Is N₂O₄ formation favoured at high or low temperature? Explain.",
          s: "(a) ΔG° = ΔH° − TΔS° = −57.2 kJ − (298 K)(−0.1758 kJ/K) = −57.2 + 52.4 = −4.8 kJ;  (b) K = e^(−ΔG°/RT) = e^(4800 ÷ (8.314 × 298)) = e^1.94 ≈ 7.0;  (c) Low temperature. The reaction is exothermic with ΔS° < 0, so ΔG° is negative only while the −TΔS° penalty is small: below about ΔH°/ΔS° = 57.2 ÷ 0.1758 ≈ 325 K.",
          r: [["(a) ΔG° ≈ −4.8 kJ, with kJ and J handled consistently", 1.5], ["(b) K ≈ 7 using ΔG° = −RT ln K", 1.5], ["(c) Low temperature, explained using the signs of ΔH° and ΔS°", 1]] },
        { t: "sa", w: 6, q: "Initial rates for A + B → products: Exp 1: [A] = 0.10 M, [B] = 0.10 M, rate = 2.0 × 10⁻³ M/s. Exp 2: [A] = 0.20 M, [B] = 0.10 M, rate = 8.0 × 10⁻³ M/s. Exp 3: [A] = 0.10 M, [B] = 0.30 M, rate = 6.0 × 10⁻³ M/s. (a) Find the order in A and in B. (b) Write the rate law and find k with units. (c) Find the rate when [A] = [B] = 0.050 M.",
          s: "(a) Exp 1 → 2: [A] doubles and the rate quadruples, so second order in A. Exp 1 → 3: [B] triples and the rate triples, so first order in B;  (b) rate = k[A]²[B]; k = 2.0 × 10⁻³ ÷ [(0.10)²(0.10)] = 2.0 M⁻² s⁻¹;  (c) rate = 2.0 × (0.050)² × 0.050 = 2.5 × 10⁻⁴ M/s.",
          r: [["Second order in A", 1], ["First order in B", 1], ["k = 2.0 M⁻² s⁻¹, including units", 1], ["Rate = 2.5 × 10⁻⁴ M/s", 1]] }
      ]
    },

    /* ---------------- CHEM*2700 ---------------- */
    c2700: {
      weeks: [1, 6],
      minutes: 50,
      covers: "Acids and bases, formal charge and resonance, naming and conformations of alkanes and cycloalkanes, stereochemistry, reading mechanisms, SN1/SN2 and E1/E2 (Organic Chemistry Ch. 1–7 core sections and Ch. 11).",
      questions: [
        { t: "mc", w: 1, q: "Which is the strongest acid?",
          o: ["Ethanol, CH₃CH₂OH", "Trifluoroacetic acid, CF₃COOH", "Acetic acid, CH₃COOH", "Phenol, C₆H₅OH"], a: 1,
          e: "The three electronegative fluorines pull electron density away from the carboxylate (inductive effect), stabilizing the conjugate base. Its pKa is about 0.2, versus 4.76 for acetic acid." },
        { t: "mc", w: 1, q: "What is the formal charge on oxygen in the hydronium ion, H₃O⁺?",
          o: ["−1", "0", "+1", "+2"], a: 2,
          e: "FC = 6 − 2 (one lone pair) − ½(6 bonding electrons) = +1." },
        { t: "mc", w: 1, q: "Which anion is stabilized by resonance?",
          o: ["Acetate, CH₃COO⁻", "Ethoxide, CH₃CH₂O⁻", "tert-Butoxide, (CH₃)₃CO⁻", "Hydroxide, OH⁻"], a: 0,
          e: "Acetate’s negative charge is shared between two equivalent oxygens. The others keep the charge on a single oxygen." },
        { t: "mc", w: 2, q: "What is the IUPAC name of (CH₃)₂CHCH₂CH(CH₃)CH₂CH₃?",
          o: ["3,5-Dimethylhexane", "2-Methyl-4-ethylpentane", "2,4-Dimethylheptane", "2,4-Dimethylhexane"], a: 3,
          e: "The longest chain has six carbons with methyls on C2 and C4, numbered from the end nearer the first branch." },
        { t: "mc", w: 2, q: "In the more stable chair of trans-1,4-dimethylcyclohexane, the methyl groups are…",
          o: ["both axial", "one axial and one equatorial", "both equatorial", "Neither chair is favoured"], a: 2,
          e: "trans-1,4 can be diaxial or diequatorial. Diequatorial avoids 1,3-diaxial strain, so it is favoured." },
        { t: "mc", w: 3, q: "How many stereocentres does 2,3-dibromobutane have, and how many stereoisomers exist?",
          o: ["2 stereocentres and 4 stereoisomers", "2 stereocentres and 3 stereoisomers", "1 stereocentre and 2 stereoisomers", "2 stereocentres and 2 stereoisomers"], a: 1,
          e: "C2 and C3 are stereocentres, giving at most 4. But (2R,3S) is identical to (2S,3R), a meso compound, so there are 3: the (R,R)/(S,S) pair and the meso form." },
        { t: "mc", w: 3, q: "(R)-2-Butanol and (S)-2-butanol differ in…",
          o: ["the direction they rotate plane-polarized light", "boiling point", "density", "solubility in water"], a: 0,
          e: "Enantiomers have identical physical properties in an achiral environment, except that they rotate plane-polarized light in opposite directions." },
        { t: "mc", w: 4, q: "In the first step of HBr adding to ethylene, what acts as the nucleophile?",
          o: ["Br⁻", "H⁺", "The C=C π bond", "The carbocation"], a: 2,
          e: "The π electrons of the alkene attack the hydrogen of HBr, forming a carbocation. Br⁻ is the nucleophile only in the second step." },
        { t: "mc", w: 4, q: "On a reaction energy diagram, an intermediate appears…",
          o: ["at an energy maximum", "in an energy minimum between two transition states", "always above the products", "at the same energy as the reactants"], a: 1,
          e: "Intermediates sit in dips between transition states; transition states are the maxima." },
        { t: "mc", w: 5, q: "Which compound reacts fastest with NaI in acetone (SN2)?",
          o: ["2-Bromobutane", "2-Bromo-2-methylpropane", "Bromobenzene", "1-Bromobutane"], a: 3,
          e: "SN2 is fastest at unhindered primary carbons. Tertiary halides and aryl halides don’t react by SN2." },
        { t: "mc", w: 5, q: "(R)-2-Bromobutane reacts with NaCN in DMSO. What is the product?",
          o: ["(R)-2-Methylbutanenitrile", "Racemic 2-methylbutanenitrile", "(S)-2-Methylbutanenitrile", "2-Butene"], a: 2,
          e: "A good nucleophile and a secondary substrate in a polar aprotic solvent react by SN2, with inversion. CN takes the top priority, like Br did, so inversion changes R to S." },
        { t: "mc", w: 6, q: "2-Bromo-2-methylbutane is heated with potassium tert-butoxide. What is the main product?",
          o: ["2-Methyl-1-butene", "2-Methyl-2-butene", "2-tert-Butoxy-2-methylbutane", "2-Methyl-2-butanol"], a: 0,
          e: "The bulky base removes the most accessible hydrogen (from CH₃) in an E2 reaction, giving the less substituted (Hofmann) alkene instead of the Zaitsev product." },
        { t: "sa", w: 6, q: "For each reaction, name the main mechanism (SN1, SN2, E1 or E2) and give the major product: (a) 1-bromopropane + NaOCH₃ in DMSO; (b) 2-bromo-2-methylpropane + NaOH, heat; (c) 2-bromo-2-methylpropane in ethanol, no added base, room temperature; (d) 2-bromopropane + NaCN in DMSO.",
          s: "(a) SN2: CH₃CH₂CH₂OCH₃ (1-methoxypropane). Strong nucleophile, unhindered primary carbon, polar aprotic solvent;  (b) E2: (CH₃)₂C=CH₂ (2-methylpropene). Strong base, tertiary substrate, heat;  (c) SN1: (CH₃)₃COCH₂CH₃ (2-ethoxy-2-methylpropane), with some E1 alkene. Weak nucleophile and a stable tertiary carbocation;  (d) SN2: (CH₃)₂CHCN (2-methylpropanenitrile). Good, weakly basic nucleophile in a polar aprotic solvent.",
          r: [["(a) SN2 and 1-methoxypropane", 1], ["(b) E2 and 2-methylpropene", 1], ["(c) SN1 and 2-ethoxy-2-methylpropane", 1], ["(d) SN2 and 2-methylpropanenitrile", 1]] },
        { t: "sa", w: 3, q: "Lactic acid is CH₃CH(OH)COOH. (a) Rank the four groups on the stereocentre by Cahn–Ingold–Prelog priority. (b) In a drawing where H points away from you, OH is at the top, COOH at the lower right and CH₃ at the lower left, is the stereocentre R or S? (c) What is the relationship between (R)- and (S)-lactic acid, and do they have the same melting point?",
          s: "(a) –OH > –COOH > –CH₃ > –H. O has the highest atomic number; the COOH carbon carries (O, O, O) versus (H, H, H) for CH₃;  (b) With H at the back, OH (top) → COOH (lower right) → CH₃ (lower left) runs clockwise, so it is R;  (c) They are enantiomers. Pure enantiomers have the same melting point; they differ only in the sign of optical rotation.",
          r: [["(a) Correct priority order", 1.5], ["(b) R", 1.5], ["(c) Enantiomers with the same melting point", 1]] },
        { t: "sa", w: 1, q: "(a) Write the equation for acetic acid (pKa 4.76) reacting with methylamine, CH₃NH₂ (pKa of CH₃NH₃⁺ = 10.6). (b) Describe the curved arrows for the proton transfer. (c) Calculate the equilibrium constant and say which side is favoured.",
          s: "(a) CH₃COOH + CH₃NH₂ ⇌ CH₃COO⁻ + CH₃NH₃⁺;  (b) An arrow from the nitrogen lone pair to the acidic H, and an arrow from the O–H bond onto the oxygen;  (c) K = 10^(pKa of product acid − pKa of reactant acid) = 10^(10.6 − 4.76) = 10^5.84 ≈ 7 × 10⁵. The products (the weaker acid, CH₃NH₃⁺) are strongly favoured.",
          r: [["(a) Correct products of the proton transfer", 1], ["(b) Both arrows, starting at electrons", 1.5], ["(c) K ≈ 7 × 10⁵", 1], ["(c) Products favoured", 0.5]] }
      ]
    },

    /* ---------------- BIOC*2580 ---------------- */
    c2580: {
      weeks: [1, 6],
      minutes: 50,
      covers: "Water, pH and buffers, amino acids and peptides, protein structure, myoglobin and hemoglobin, carbohydrates, enzyme kinetics and inhibition (Fundamentals of Biochemistry Ch. 1–7).",
      questions: [
        { t: "mc", w: 1, q: "What is the pH of 0.010 M HCl?",
          o: ["1", "12", "2", "10"], a: 2,
          e: "HCl is a strong acid, so [H⁺] = 0.010 M and pH = −log(0.010) = 2." },
        { t: "mc", w: 1, q: "An acetic acid buffer (pKa 4.76) is at pH 5.76. What is the ratio [acetate]/[acetic acid]?",
          o: ["0.1", "1", "100", "10"], a: 3,
          e: "log(ratio) = pH − pKa = 1, so the ratio is 10." },
        { t: "mc", w: 2, q: "What is the approximate net charge of the tripeptide Lys–Gly–Asp at pH 7?",
          o: ["+2", "0", "+1", "−1"], a: 1,
          e: "N-terminus +1, Lys side chain +1, Asp side chain −1, C-terminus −1: a total of 0." },
        { t: "mc", w: 2, q: "Which amino acid has a side chain with a pKa near physiological pH, making it common in acid–base catalysis?",
          o: ["Histidine", "Leucine", "Serine", "Glycine"], a: 0,
          e: "Histidine’s imidazole side chain has a pKa of about 6, so it can donate or accept a proton near pH 7." },
        { t: "mc", w: 3, q: "Which interaction stabilizes an α-helix?",
          o: ["Disulfide bonds between neighbouring residues", "Hydrogen bonds between side chains only", "Hydrogen bonds from the C=O of residue n to the N–H of residue n + 4", "Ionic bonds between the N- and C-termini"], a: 2,
          e: "The helix is held by backbone hydrogen bonds running parallel to the helix axis, from residue n to n + 4." },
        { t: "mc", w: 3, q: "Urea and heat denature proteins mainly by disrupting…",
          o: ["peptide bonds", "the amino-acid sequence", "noncovalent interactions", "disulfide bonds only"], a: 2,
          e: "Denaturation unfolds the protein by breaking hydrogen bonds and hydrophobic interactions. The covalent backbone and sequence stay intact." },
        { t: "mc", w: 4, q: "Compared with hemoglobin, myoglobin…",
          o: ["binds O₂ cooperatively", "has a higher O₂ affinity (lower P₅₀)", "has a sigmoidal binding curve", "is regulated by BPG"], a: 1,
          e: "Myoglobin is a single chain with a hyperbolic curve and a low P₅₀. Cooperativity, the sigmoidal curve and BPG regulation belong to hemoglobin." },
        { t: "mc", w: 4, q: "Which change increases O₂ release from hemoglobin in exercising muscle?",
          o: ["A rise in pH", "A drop in CO₂", "A fall in BPG", "A drop in pH"], a: 3,
          e: "More H⁺ (lower pH) stabilizes the T state and lowers O₂ affinity: the Bohr effect." },
        { t: "mc", w: 5, q: "D-Glucose and D-galactose are…",
          o: ["epimers", "enantiomers", "anomers", "an aldose and a ketose"], a: 0,
          e: "They differ in configuration at only one stereocentre (C4), which makes them epimers. Both are aldohexoses." },
        { t: "mc", w: 5, q: "Which disaccharide is non-reducing?",
          o: ["Maltose", "Lactose", "Sucrose", "Cellobiose"], a: 2,
          e: "Sucrose joins the anomeric carbons of glucose and fructose, so neither can open to a free carbonyl." },
        { t: "mc", w: 6, q: "An enzyme has Km = 4.0 mM. At what substrate concentration is v₀ = ½Vmax?",
          o: ["2.0 mM", "8.0 mM", "It depends on the enzyme concentration", "4.0 mM"], a: 3,
          e: "By definition, Km is the substrate concentration that gives half the maximum rate." },
        { t: "mc", w: 6, q: "A competitive inhibitor…",
          o: ["lowers Vmax", "raises the apparent Km and leaves Vmax unchanged", "lowers Km and Vmax by the same factor", "binds only the enzyme–substrate complex"], a: 1,
          e: "It competes with substrate for the active site, so enough substrate can still reach Vmax, but more is needed to reach half of it." },
        { t: "sa", w: 1, q: "You need 1.0 L of 0.10 M phosphate buffer at pH 7.20, made from NaH₂PO₄ (acid form) and Na₂HPO₄ (base form); pKa = 6.86. (a) Find the ratio [HPO₄²⁻]/[H₂PO₄⁻]. (b) Find the concentration of each form. (c) Which component would you add more of to raise the pH?",
          s: "(a) log(ratio) = 7.20 − 6.86 = 0.34, so ratio = 10^0.34 ≈ 2.19;  (b) [H₂PO₄⁻] = 0.10 ÷ (1 + 2.19) ≈ 0.031 M and [HPO₄²⁻] ≈ 0.10 − 0.031 = 0.069 M;  (c) More Na₂HPO₄, the base form, which raises [A⁻]/[HA].",
          r: [["(a) Ratio ≈ 2.2", 1.5], ["(b) [H₂PO₄⁻] ≈ 0.031 M", 1], ["(b) [HPO₄²⁻] ≈ 0.069 M", 1], ["(c) Add the base form, Na₂HPO₄", 0.5]] },
        { t: "sa", w: 6, q: "An enzyme gives v₀ = 50 µM/min at [S] = 1.0 mM and v₀ = 100 µM/min at [S] = 3.0 mM. (a) Use the Michaelis–Menten equation to find Km and Vmax. (b) What is v₀ at [S] = 9.0 mM? (c) If [E]total = 2.0 µM, what is kcat?",
          s: "(a) 50 = Vmax(1)/(Km + 1) and 100 = Vmax(3)/(Km + 3). Dividing: 2 = 3(Km + 1)/(Km + 3), so 2Km + 6 = 3Km + 3 and Km = 3.0 mM. Then Vmax = 50 × (3 + 1) = 200 µM/min;  (b) v₀ = 200 × 9/(3 + 9) = 150 µM/min;  (c) kcat = Vmax/[E]total = 200 µM/min ÷ 2.0 µM = 100 min⁻¹ (about 1.7 s⁻¹).",
          r: [["Set up two Michaelis–Menten equations (or an equivalent method)", 1], ["Km = 3.0 mM and Vmax = 200 µM/min", 1.5], ["(b) v₀ = 150 µM/min", 0.75], ["(c) kcat = 100 min⁻¹", 0.75]] },
        { t: "sa", w: 4, q: "Explain cooperative O₂ binding by hemoglobin: (a) what differs between the T and R states, (b) why the binding curve is sigmoidal, and (c) why this makes hemoglobin a better O₂ carrier than a myoglobin-like protein would be.",
          s: "(a) The T (tense) state has low O₂ affinity and the R (relaxed) state has high affinity. O₂ binding to one subunit shifts the others toward R;  (b) Affinity rises as sites fill, so binding is slow at low pO₂, then rises steeply: an S-shaped curve;  (c) Hemoglobin is nearly saturated in the lungs but, on the steep part of the curve, releases a large fraction of its O₂ at tissue pO₂. A high-affinity, non-cooperative carrier like myoglobin would stay mostly bound and deliver little.",
          r: [["(a) T = low affinity, R = high affinity, and binding shifts subunits toward R", 1.5], ["(b) Rising affinity as sites fill gives the sigmoidal shape", 1], ["(c) Loads fully in the lungs and unloads much more in tissues than myoglobin would", 1.5]] }
      ]
    },

    /* ---------------- IPS*1500 ---------------- */
    c1500: {
      weeks: [1, 6],
      minutes: 50,
      covers: "Functions, units and vectors, limits, the derivative and differentiation rules, 1D and 2D kinematics, Newton’s laws and max/min problems (Calculus Vol. 1 Ch. 1–3 and §4.1–4.5; University Physics Vol. 1 Ch. 1–5). Use g = 9.8 m/s².",
      questions: [
        { t: "mc", w: 1, q: "What is the magnitude of the vector A = (6, −8)?",
          o: ["2", "14", "10", "100"], a: 2,
          e: "|A| = √(6² + 8²) = √100 = 10." },
        { t: "mc", w: 1, q: "If a is an acceleration and t is a time, which expression has units of velocity?",
          o: ["a/t", "a·t", "a·t²", "a/t²"], a: 1,
          e: "(m/s²)(s) = m/s." },
        { t: "mc", w: 2, q: "Evaluate lim(x→2) (x² − 4)/(x − 2).",
          o: ["0", "4", "2", "The limit does not exist"], a: 1,
          e: "Factor to (x − 2)(x + 2)/(x − 2) = x + 2, which approaches 4." },
        { t: "mc", w: 2, q: "Evaluate lim(x→0) sin(3x)/x.",
          o: ["3", "1", "0", "1/3"], a: 0,
          e: "sin(3x)/x = 3 · sin(3x)/(3x), which approaches 3 × 1 = 3." },
        { t: "mc", w: 3, q: "x(t) = 2t³ − 3t² (in metres). What is the velocity at t = 2 s?",
          o: ["4 m/s", "24 m/s", "18 m/s", "12 m/s"], a: 3,
          e: "v(t) = 6t² − 6t, so v(2) = 24 − 12 = 12 m/s." },
        { t: "mc", w: 3, q: "A stone is thrown straight up at 15 m/s. Taking up as positive, what is its velocity 2.0 s later?",
          o: ["+4.6 m/s", "−19.6 m/s", "−4.6 m/s", "0 m/s"], a: 2,
          e: "v = v₀ − gt = 15 − 19.6 = −4.6 m/s. It is already on the way down." },
        { t: "mc", w: 4, q: "d/dx [e^(2x) sin x] = ?",
          o: ["2e^(2x) cos x", "e^(2x)(2 sin x + cos x)", "2e^(2x) sin x", "e^(2x) cos x"], a: 1,
          e: "Product rule with the chain rule: 2e^(2x) sin x + e^(2x) cos x." },
        { t: "mc", w: 4, q: "d/dx √(1 + x²) = ?",
          o: ["x/√(1 + x²)", "1/(2√(1 + x²))", "2x√(1 + x²)", "x/(2√(1 + x²))"], a: 0,
          e: "Chain rule: ½(1 + x²)^(−½) · 2x = x/√(1 + x²)." },
        { t: "mc", w: 5, q: "A ball rolls horizontally off a 20 m cliff at 12 m/s. About how far from the base of the cliff does it land?",
          o: ["12 m", "49 m", "98 m", "24 m"], a: 3,
          e: "Fall time: t = √(2h/g) = √(40/9.8) ≈ 2.0 s. Horizontal distance = 12 × 2.0 ≈ 24 m." },
        { t: "mc", w: 5, q: "An object moves at a constant 4.0 m/s around a circle of radius 2.0 m. What is its acceleration?",
          o: ["0 m/s²", "2.0 m/s² toward the centre", "8.0 m/s² toward the centre", "8.0 m/s² along the direction of motion"], a: 2,
          e: "a = v²/r = 16/2.0 = 8.0 m/s², pointing toward the centre. Constant speed doesn’t mean zero acceleration; the direction keeps changing." },
        { t: "mc", w: 6, q: "A 5.0 kg box is pulled across a frictionless floor by a 20 N force at 30° above the horizontal. What is its acceleration?",
          o: ["2.0 m/s²", "4.0 m/s²", "3.5 m/s²", "6.9 m/s²"], a: 2,
          e: "Only the horizontal component accelerates it: a = (20 cos 30°)/5.0 = 17.3/5.0 ≈ 3.5 m/s²." },
        { t: "mc", w: 6, q: "A 60 kg person stands on a scale in an elevator. The scale reads 540 N. The elevator is…",
          o: ["at rest", "accelerating upward at 0.8 m/s²", "in free fall", "accelerating downward at 0.8 m/s²"], a: 3,
          e: "mg = 588 N. N − mg = ma gives a = (540 − 588)/60 = −0.8 m/s², so the acceleration is downward. (It could be moving up while slowing down.)" },
        { t: "sa", w: 5, q: "A ball is kicked from level ground at 25 m/s, 40° above the horizontal. Find (a) the horizontal and vertical components of the initial velocity, (b) the time of flight, (c) the maximum height and (d) the range.",
          s: "(a) vₓ = 25 cos 40° ≈ 19.2 m/s and v_y = 25 sin 40° ≈ 16.1 m/s;  (b) T = 2v_y/g = 2(16.07)/9.8 ≈ 3.28 s;  (c) H = v_y²/(2g) = (16.07)²/19.6 ≈ 13.2 m;  (d) R = vₓT = 19.15 × 3.28 ≈ 62.8 m (check: v₀² sin 80°/g ≈ 62.8 m).",
          r: [["(a) Both components", 1], ["(b) Time of flight ≈ 3.3 s", 1], ["(c) Maximum height ≈ 13 m", 1], ["(d) Range ≈ 63 m", 1]] },
        { t: "sa", w: 6, q: "A 4.0 kg block on a frictionless horizontal table is tied by a light string, running over a frictionless pulley, to a 2.0 kg block hanging over the edge. (a) Describe the forces on each block. (b) Find the acceleration. (c) Find the tension in the string.",
          s: "(a) Table block: weight down, normal force up, tension toward the pulley. Hanging block: weight down, tension up;  (b) Table block: T = 4.0a. Hanging block: 2.0(9.8) − T = 2.0a. Adding: 19.6 = 6.0a, so a ≈ 3.27 m/s²;  (c) T = 4.0 × 3.27 ≈ 13.1 N (check: 19.6 − 13.1 = 6.5 = 2.0 × 3.27).",
          r: [["(a) Correct forces on both blocks", 1], ["(b) Newton’s second law written for each block", 1], ["(b) a ≈ 3.3 m/s²", 1], ["(c) T ≈ 13 N", 1]] },
        { t: "sa", w: 6, q: "A rectangular garden against a wall is fenced on the other three sides with 40 m of fencing. Let x be the length of each side perpendicular to the wall. (a) Write the area A as a function of x. (b) Use calculus to find the x that maximizes the area, and give the garden’s dimensions and area. (c) Show that it is a maximum.",
          s: "(a) The side parallel to the wall is 40 − 2x, so A(x) = x(40 − 2x) = 40x − 2x², for 0 < x < 20;  (b) A′(x) = 40 − 4x = 0, so x = 10 m. The garden is 10 m × 20 m, with area 200 m²;  (c) A″(x) = −4 < 0, so x = 10 m is a maximum.",
          r: [["(a) A(x) = 40x − 2x²", 1], ["(b) A′(x) = 0 gives x = 10 m", 1.5], ["(b) Dimensions 10 m × 20 m and area 200 m²", 1], ["(c) Second-derivative (or equivalent) check", 0.5]] }
      ]
    }
  };
})(typeof self !== "undefined" ? self : this);
