/* Practice final exams, one per course: cumulative (weeks 1–12), weighted toward weeks 7–12.
   Same question format as practice-exams.js. Loaded after it and added to the same PRACTICE_EXAMS object. */
(function (root) {
  "use strict";
  var E = root.PRACTICE_EXAMS = root.PRACTICE_EXAMS || {};

  /* ---------------- CHEM*1050 ---------------- */
  E["c1050-final"] = {
    kind: "final",
    weeks: [1, 12],
    minutes: 120,
    covers: "Everything in the course, weighted toward kinetics (integrated rate laws, Arrhenius, mechanisms, catalysis) and electrochemistry (redox, galvanic cells, E°, ΔG° and K, Nernst, electrolysis). Chemistry 2e Ch. 4.2, 5, 12, 13.1–13.3, 16, 17. Use R = 8.314 J/mol·K and F = 96,485 C/mol.",
    questions: [
      { t: "mc", w: 1, q: "Burning 1.00 g of a fuel in a bomb calorimeter with heat capacity 10.0 kJ/°C raises the temperature by 4.50 °C. How much heat does the fuel release per gram?",
        o: ["4.50 kJ", "45.0 kJ", "2.22 kJ", "450 kJ"], a: 1,
        e: "q = C·ΔT = 10.0 kJ/°C × 4.50 °C = 45.0 kJ for 1.00 g." },
      { t: "mc", w: 2, q: "Which has the highest standard molar entropy?",
        o: ["C(s, diamond)", "H₂O(l)", "Ar(g)", "C₃H₈(g)"], a: 3,
        e: "Gases have far more entropy than solids or liquids, and propane’s many atoms give it more vibrational and rotational microstates than argon (about 270 vs 155 J/mol·K)." },
      { t: "mc", w: 3, q: "Which set of signs describes ice melting at 25 °C?",
        o: ["ΔH > 0, ΔS > 0, ΔG < 0", "ΔH < 0, ΔS < 0, ΔG < 0", "ΔH > 0, ΔS < 0, ΔG > 0", "ΔH < 0, ΔS > 0, ΔG > 0"], a: 0,
        e: "Melting absorbs heat (ΔH > 0) and increases disorder (ΔS > 0). Above 0 °C the TΔS term wins, so ΔG < 0." },
      { t: "mc", w: 4, q: "A reaction at 298 K has K = 4.5 × 10³. Which statement is true?",
        o: ["ΔG° is positive and reactants are favoured", "ΔG° is negative and products are favoured", "ΔG° = 0", "ΔG° can’t be found from K"], a: 1,
        e: "ΔG° = −RT ln K, and ln K > 0 when K > 1, so ΔG° is negative." },
      { t: "mc", w: 6, q: "For 2 NO + O₂ → 2 NO₂ the rate law is rate = k[NO]²[O₂]. What is the overall order?",
        o: ["3", "1", "2", "5"], a: 0,
        e: "Add the exponents: 2 + 1 = 3." },
      { t: "mc", w: 6, q: "A reactant is second order. If its concentration is tripled, the rate increases by a factor of…",
        o: ["3", "9", "6", "27"], a: 1,
        e: "Rate ∝ [A]², so 3² = 9." },
      { t: "mc", w: 7, q: "A first-order reaction has a half-life of 20 min. What fraction of the reactant remains after 1 hour?",
        o: ["1/3", "1/6", "1/8", "1/9"], a: 2,
        e: "60 min is three half-lives: (½)³ = 1/8." },
      { t: "mc", w: 7, q: "A plot of 1/[A] against time is a straight line with a positive slope. The reaction is…",
        o: ["second order", "zero order", "first order", "third order"], a: 0,
        e: "The second-order integrated rate law is 1/[A] = 1/[A]₀ + kt, a line with slope k." },
      { t: "mc", w: 7, q: "A first-order reaction has k = 3.5 × 10⁻² s⁻¹. How long does it take [A] to fall from 0.80 M to 0.20 M?",
        o: ["20 s", "40 s", "11 s", "80 s"], a: 1,
        e: "t = ln([A]₀/[A])/k = ln 4 ÷ 0.035 s⁻¹ = 1.386 ÷ 0.035 ≈ 40 s (two half-lives of about 20 s)." },
      { t: "mc", w: 8, q: "A catalyst speeds up a reaction by…",
        o: ["increasing ΔH", "increasing K", "raising the temperature of the mixture", "providing a pathway with a lower activation energy"], a: 3,
        e: "A catalyst lowers Ea for both directions. It doesn’t change ΔH, ΔG°, K or the temperature." },
      { t: "mc", w: 8, q: "Mechanism: Step 1, A + B ⇌ C (fast); Step 2, C + B → D (slow). What is the overall reaction?",
        o: ["A + B → D", "A + 2B → D", "C + B → D", "A + B + C → D"], a: 1,
        e: "Add the steps and cancel the intermediate C: A + 2B → D." },
      { t: "mc", w: 8, q: "Raising the temperature from 300 K to 310 K doubles a rate constant. The activation energy is about…",
        o: ["540 kJ/mol", "5.4 kJ/mol", "0.54 kJ/mol", "54 kJ/mol"], a: 3,
        e: "Ea = R ln(k₂/k₁) ÷ (1/T₁ − 1/T₂) = (8.314)(0.693) ÷ (1.075 × 10⁻⁴) ≈ 5.4 × 10⁴ J/mol = 54 kJ/mol." },
      { t: "mc", w: 9, q: "What is the oxidation number of sulfur in H₂SO₄?",
        o: ["−2", "+4", "+6", "+2"], a: 2,
        e: "2(+1) + S + 4(−2) = 0, so S = +6." },
      { t: "mc", w: 9, q: "In a galvanic cell, electrons flow through the external wire…",
        o: ["from cathode to anode", "through the salt bridge", "in both directions equally", "from anode to cathode"], a: 3,
        e: "Oxidation at the anode releases electrons, which travel through the wire to the cathode. Ions, not electrons, move through the salt bridge." },
      { t: "mc", w: 10, q: "Which is the strongest oxidizing agent? E°: Ag⁺/Ag +0.80 V; Cu²⁺/Cu +0.34 V; Zn²⁺/Zn −0.76 V; Mg²⁺/Mg −2.37 V.",
        o: ["Mg²⁺", "Zn²⁺", "Cu²⁺", "Ag⁺"], a: 3,
        e: "The species with the most positive reduction potential is most easily reduced, so it is the strongest oxidizing agent." },
      { t: "mc", w: 10, q: "A cell has E°cell = −0.25 V. Which is true under standard conditions?",
        o: ["It is spontaneous and K > 1", "It is not spontaneous and K < 1", "ΔG° < 0", "It is at equilibrium"], a: 1,
        e: "ΔG° = −nFE° is positive when E° is negative, so the reaction isn’t spontaneous and K < 1." },
      { t: "mc", w: 10, q: "For Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s) (E° = 1.10 V), increasing [Cu²⁺] will…",
        o: ["not change E", "decrease E", "increase E", "make E negative"], a: 2,
        e: "Q = [Zn²⁺]/[Cu²⁺] gets smaller, so the Nernst term −(0.0592/n) log Q becomes more positive and E rises." },
      { t: "mc", w: 11, q: "How long must a 5.00 A current run to deposit 2.00 g of silver (Ag⁺ + e⁻ → Ag, M = 107.9 g/mol)?",
        o: ["358 s", "179 s", "716 s", "36 s"], a: 0,
        e: "mol Ag = 2.00/107.9 = 0.0185 = mol e⁻. Charge = 0.0185 × 96,485 = 1790 C, and t = 1790 C ÷ 5.00 A ≈ 358 s." },
      { t: "mc", w: 11, q: "Which metal could act as a sacrificial anode to protect iron (E° of Fe²⁺/Fe = −0.44 V)?",
        o: ["Copper (+0.34 V)", "Silver (+0.80 V)", "Magnesium (−2.37 V)", "Lead (−0.13 V)"], a: 2,
        e: "A sacrificial anode must be oxidized more easily than iron, so it needs a more negative E°. Only magnesium qualifies." },
      { t: "mc", w: 12, q: "A reaction has ΔG° < 0 but is very slow at room temperature. The best explanation is…",
        o: ["its activation energy is high", "K is less than 1", "the reaction is endothermic", "ΔS° is negative"], a: 0,
        e: "Thermodynamics says the reaction is favourable; kinetics (a high Ea) controls how fast it goes. K < 1 would contradict ΔG° < 0." },
      { t: "sa", w: 7, q: "The decomposition of N₂O₅ is first order, with k = 5.0 × 10⁻⁴ s⁻¹ at 45 °C. (a) Find the half-life. (b) Starting from 0.50 M, find [N₂O₅] after 30.0 min. (c) How long until 90% has decomposed? (d) At 55 °C, k = 1.5 × 10⁻³ s⁻¹. Find the activation energy.",
        s: "(a) t½ = 0.693/k = 0.693 ÷ 5.0 × 10⁻⁴ s⁻¹ ≈ 1390 s (about 23 min);  (b) ln[A] = ln(0.50) − (5.0 × 10⁻⁴)(1800 s), so [A] = 0.50·e^(−0.90) ≈ 0.20 M;  (c) 10% remains: t = ln(1/0.10)/k = 2.303 ÷ 5.0 × 10⁻⁴ ≈ 4600 s (about 77 min);  (d) ln(1.5 × 10⁻³ / 5.0 × 10⁻⁴) = ln 3 = 1.099 = (Ea/8.314)(1/318 K − 1/328 K). The bracket is 9.58 × 10⁻⁵ K⁻¹, so Ea ≈ 9.5 × 10⁴ J/mol = 95 kJ/mol.",
        r: [["(a) Half-life ≈ 1390 s", 1], ["(b) [N₂O₅] ≈ 0.20 M, with time converted to seconds", 1.5], ["(c) About 4600 s", 1], ["(d) Ea ≈ 95 kJ/mol, with temperatures in kelvin", 1.5]] },
      { t: "sa", w: 10, q: "A galvanic cell is Al(s) | Al³⁺(aq) ‖ Ni²⁺(aq) | Ni(s). E°(Al³⁺/Al) = −1.66 V and E°(Ni²⁺/Ni) = −0.26 V. (a) Write the balanced overall reaction. (b) Calculate E°cell. (c) Calculate ΔG°. (d) Calculate E at 298 K when [Al³⁺] = 0.010 M and [Ni²⁺] = 1.0 M.",
        s: "(a) Anode: Al → Al³⁺ + 3e⁻ (×2). Cathode: Ni²⁺ + 2e⁻ → Ni (×3). Overall: 2 Al(s) + 3 Ni²⁺(aq) → 2 Al³⁺(aq) + 3 Ni(s), with n = 6;  (b) E°cell = −0.26 − (−1.66) = +1.40 V;  (c) ΔG° = −nFE° = −6 × 96,485 × 1.40 ≈ −8.10 × 10⁵ J = −810 kJ;  (d) Q = [Al³⁺]²/[Ni²⁺]³ = (0.010)²/(1.0)³ = 1.0 × 10⁻⁴. E = 1.40 − (0.0592/6) log(1.0 × 10⁻⁴) = 1.40 + 0.039 ≈ 1.44 V.",
        r: [["(a) Balanced with 6 electrons transferred", 1.5], ["(b) E°cell = +1.40 V", 1], ["(c) ΔG° ≈ −810 kJ using n = 6", 1.5], ["(d) E ≈ 1.44 V with the correct Q", 1]] },
      { t: "sa", w: 11, q: "Electrolysis of molten NaCl gives sodium metal at one electrode and chlorine gas at the other. (a) Write both half-reactions and name the electrode where each happens. (b) What mass of sodium forms when 10.0 A flows for 1.00 h? (M = 22.99 g/mol) (c) What volume of Cl₂ forms at STP (22.4 L/mol)?",
        s: "(a) Cathode (reduction): Na⁺ + e⁻ → Na(l). Anode (oxidation): 2 Cl⁻ → Cl₂(g) + 2e⁻;  (b) Charge = 10.0 A × 3600 s = 36,000 C. mol e⁻ = 36,000 ÷ 96,485 = 0.373, which equals mol Na. Mass = 0.373 × 22.99 ≈ 8.58 g;  (c) mol Cl₂ = 0.373 ÷ 2 = 0.187, and V = 0.187 × 22.4 ≈ 4.18 L.",
        r: [["(a) Cathode half-reaction and electrode", 1], ["(a) Anode half-reaction and electrode", 1], ["(b) Mass of sodium ≈ 8.58 g", 2], ["(c) Volume of Cl₂ ≈ 4.18 L", 1]] },
      { t: "sa", w: 4, q: "For CaCO₃(s) → CaO(s) + CO₂(g): ΔH° = +178.3 kJ and ΔS° = +160.6 J/K. (a) Calculate ΔG° at 298 K and say whether the reaction is spontaneous. (b) Estimate the lowest temperature at which it becomes spontaneous. (c) Calculate K at 298 K and explain what it says about the CO₂ pressure over limestone.",
        s: "(a) ΔG° = 178.3 − (298)(0.1606) = 178.3 − 47.9 = +130.4 kJ, so it is not spontaneous at 298 K;  (b) T = ΔH°/ΔS° = 178,300 ÷ 160.6 ≈ 1110 K (about 840 °C);  (c) K = e^(−130,400 ÷ (8.314 × 298)) = e^(−52.6) ≈ 1.4 × 10⁻²³. Here K equals the equilibrium CO₂ pressure (in bar), which is vanishingly small, so limestone doesn’t decompose at room temperature.",
        r: [["(a) ΔG° ≈ +130 kJ and not spontaneous", 1.5], ["(b) About 1110 K", 1.5], ["(c) K ≈ 1 × 10⁻²³", 1], ["(c) Explains that K is the CO₂ pressure, so essentially no decomposition", 1]] }
    ]
  };

  /* ---------------- CHEM*2700 ---------------- */
  E["c2700-final"] = {
    kind: "final",
    weeks: [1, 12],
    minutes: 120,
    covers: "Everything in the course, weighted toward alkene reactions, radical reactions, aromaticity and electrophilic aromatic substitution, nucleophilic addition to aldehydes and ketones, and nucleophilic acyl substitution (Organic Chemistry Ch. 1–11 core, 15, 16, 19, 20.3, 21).",
    questions: [
      { t: "mc", w: 1, q: "Which base is strong enough to deprotonate ethanol (pKa 16) essentially completely?",
        o: ["NaHCO₃ (pKa of H₂CO₃ ≈ 6.4)", "NaOH (pKa of H₂O 15.7)", "NaNH₂ (pKa of NH₃ ≈ 36)", "CH₃COONa (pKa of CH₃COOH 4.76)"], a: 2,
        e: "The equilibrium lies far toward the weaker acid only if the base’s conjugate acid is much weaker than ethanol. NH₃ (pKa 36) is; H₂O (15.7) gives only a partial equilibrium." },
      { t: "mc", w: 2, q: "How many constitutional isomers have the formula C₅H₁₂?",
        o: ["2", "3", "4", "5"], a: 1,
        e: "Pentane, 2-methylbutane and 2,2-dimethylpropane." },
      { t: "mc", w: 3, q: "Which compound is chiral?",
        o: ["2-Chlorobutane", "2-Chloropropane", "1-Chlorobutane", "Chloromethane"], a: 0,
        e: "C2 of 2-chlorobutane carries four different groups: Cl, H, CH₃ and CH₂CH₃. The others have no such carbon." },
      { t: "mc", w: 5, q: "Which nucleophile reacts fastest with bromomethane in DMSO?",
        o: ["H₂O", "CH₃OH", "CH₃COO⁻", "CH₃O⁻"], a: 3,
        e: "In a polar aprotic solvent, nucleophilicity follows basicity for the same attacking atom, and negatively charged methoxide is the strongest base here." },
      { t: "mc", w: 5, q: "Which alkyl halide reacts fastest by SN1 in water?",
        o: ["1-Bromobutane", "2-Bromobutane", "Bromomethane", "2-Bromo-2-methylpropane"], a: 3,
        e: "The SN1 rate depends on carbocation stability, and only the tertiary halide forms a stable (tertiary) carbocation." },
      { t: "mc", w: 6, q: "2-Bromobutane reacts with sodium ethoxide in ethanol. What is the main product?",
        o: ["1-Butene", "trans-2-Butene", "cis-2-Butene", "2-Ethoxybutane"], a: 1,
        e: "A strong, small base with a secondary halide favours E2, giving the Zaitsev alkene; the trans isomer is more stable than cis." },
      { t: "mc", w: 7, q: "What is the major product when HCl adds to 1-methylcyclohexene?",
        o: ["1-Chloro-1-methylcyclohexane", "1-Chloro-2-methylcyclohexane", "(Chloromethyl)cyclohexane", "Methylcyclohexane"], a: 0,
        e: "Protonation gives the tertiary carbocation at C1 (Markovnikov), and chloride adds there." },
      { t: "mc", w: 7, q: "What is the degree of unsaturation of styrene, C₈H₈?",
        o: ["4", "6", "3", "5"], a: 3,
        e: "(2 × 8 + 2 − 8)/2 = 5: the benzene ring (1 ring + 3 π bonds) plus the vinyl C=C." },
      { t: "mc", w: 8, q: "Which reagents convert 1-hexene into 1-hexanol?",
        o: ["H₂O, H₂SO₄", "1. Hg(OAc)₂, H₂O  2. NaBH₄", "1. BH₃·THF  2. H₂O₂, NaOH", "H₂, Pd/C"], a: 2,
        e: "Hydroboration–oxidation places OH on the less substituted carbon. The first two give 2-hexanol (Markovnikov); hydrogenation gives hexane." },
      { t: "mc", w: 8, q: "Ozonolysis (O₃, then Zn/H₃O⁺) of an alkene gives only acetone, (CH₃)₂C=O. What was the alkene?",
        o: ["2-Methylpropene", "2,3-Dimethyl-2-butene", "2-Butene", "2-Methyl-2-butene"], a: 1,
        e: "(CH₃)₂C=C(CH₃)₂ splits into two identical (CH₃)₂C=O pieces." },
      { t: "mc", w: 8, q: "cis-2-Butene reacts with Br₂. The product is…",
        o: ["meso-2,3-dibromobutane", "racemic (2R,3R)- and (2S,3S)-2,3-dibromobutane", "1,2-dibromobutane", "2-bromobutane"], a: 1,
        e: "Bromine adds anti through a bromonium ion. Anti addition to the cis alkene gives the racemic pair; anti addition to trans-2-butene gives the meso compound." },
      { t: "mc", w: 9, q: "Why does radical chlorination of propane give a mixture of 1-chloropropane and 2-chloropropane?",
        o: ["Cl· is highly reactive and not very selective", "The primary radical is more stable", "Chlorine adds through a carbocation", "Propane has only one type of hydrogen"], a: 0,
        e: "Abstraction by Cl· is exothermic with an early transition state, so radical stability matters little and both kinds of H react." },
      { t: "mc", w: 9, q: "Which radical is the most stable?",
        o: ["Methyl, ·CH₃", "Ethyl, ·CH₂CH₃", "Vinyl, CH₂=CH·", "tert-Butyl, ·C(CH₃)₃"], a: 3,
        e: "Radical stability follows 3° > 2° > 1° > methyl, like carbocations. Vinyl radicals are especially unstable." },
      { t: "mc", w: 10, q: "Which compound is aromatic?",
        o: ["Cyclobutadiene", "Cyclooctatetraene", "Pyridine", "1,3-Cyclohexadiene"], a: 2,
        e: "Pyridine is planar, cyclic and fully conjugated with 6 π electrons (the N lone pair isn’t part of the π system). Cyclobutadiene is antiaromatic, cyclooctatetraene is non-planar, and cyclohexadiene isn’t fully conjugated." },
      { t: "mc", w: 10, q: "Nitration of methoxybenzene (anisole) gives mainly…",
        o: ["meta-nitroanisole", "ortho- and para-nitroanisole", "nitrobenzene and methanol", "no reaction, because –OCH₃ deactivates the ring"], a: 1,
        e: "–OCH₃ donates electrons by resonance, activating the ring and directing to the ortho and para positions." },
      { t: "mc", w: 10, q: "Friedel–Crafts alkylation of benzene with 1-chloropropane and AlCl₃ gives mainly isopropylbenzene. Why?",
        o: ["The primary carbocation rearranges by a hydride shift to a more stable secondary carbocation", "Isopropyl groups are meta directors", "AlCl₃ reduces the propyl group", "Benzene reacts only with secondary carbons"], a: 0,
        e: "Carbocation rearrangement before attack is a known limitation of Friedel–Crafts alkylation. Acylation followed by reduction avoids it." },
      { t: "mc", w: 11, q: "Which reagent forms a new carbon–carbon bond with an aldehyde?",
        o: ["NaBH₄", "CH₃MgBr, then H₃O⁺", "H₂O, H⁺", "CH₃OH, H⁺"], a: 1,
        e: "A Grignard reagent adds a carbon nucleophile to the C=O. NaBH₄ adds hydride, and water or alcohols add oxygen." },
      { t: "mc", w: 11, q: "Cyclohexanone is heated with excess methanol and an acid catalyst while water is removed. The product is…",
        o: ["cyclohexanol", "an enamine", "an acetal, 1,1-dimethoxycyclohexane", "a hemiacetal that can’t react further"], a: 2,
        e: "Acid catalysis with excess alcohol goes through the hemiacetal to the acetal; removing water drives the equilibrium forward." },
      { t: "mc", w: 12, q: "Which carboxylic acid derivative is the most reactive toward nucleophilic acyl substitution?",
        o: ["Ethyl acetate", "Acetamide", "Acetic anhydride", "Acetyl chloride"], a: 3,
        e: "Chloride is the best leaving group and gives the least resonance donation into the C=O. The order is acid chloride > anhydride > ester > amide." },
      { t: "mc", w: 12, q: "Propanoic acid is treated with SOCl₂, then with excess dimethylamine. What forms?",
        o: ["N,N-Dimethylpropanamide", "Methyl propanoate", "Propanoyl chloride only", "Propylamine"], a: 0,
        e: "SOCl₂ makes the acid chloride; the amine then substitutes for chloride to give the amide (the extra amine absorbs the HCl)." },
      { t: "sa", w: 8, q: "Give the reagents that convert 1-methylcyclohexene into each product: (a) 1-methylcyclohexanol; (b) trans-2-methylcyclohexanol; (c) methylcyclohexane; (d) 6-oxoheptanal (the ring cut open); (e) trans-1,2-dibromo-1-methylcyclohexane.",
        s: "(a) 1. Hg(OAc)₂, H₂O  2. NaBH₄ (Markovnikov; H₂O/H₂SO₄ also works);  (b) 1. BH₃·THF  2. H₂O₂, NaOH (anti-Markovnikov, syn addition);  (c) H₂, Pd/C;  (d) 1. O₃  2. Zn, H₃O⁺ (or (CH₃)₂S), which cleaves the C=C into a ketone and an aldehyde;  (e) Br₂ in CH₂Cl₂ (anti addition through a bromonium ion).",
        r: [["(a) Markovnikov hydration reagents", 1], ["(b) Hydroboration–oxidation", 1], ["(c) Catalytic hydrogenation", 1], ["(d) Ozonolysis with a reductive workup", 1], ["(e) Br₂", 1]] },
      { t: "sa", w: 10, q: "Starting from benzene, give reagents and the order of steps to make (a) m-bromonitrobenzene and (b) p-bromonitrobenzene. (c) Explain why the nitro group directs meta.",
        s: "(a) Nitrate first (HNO₃, H₂SO₄), then brominate (Br₂, FeBr₃). –NO₂ is a meta director, so Br enters meta;  (b) Brominate first (Br₂, FeBr₃), then nitrate (HNO₃, H₂SO₄). –Br directs ortho/para, and the para product is separated from the ortho;  (c) –NO₂ withdraws electrons by induction and resonance. Attack at ortho or para puts the positive charge of the arenium ion next to the positively charged nitrogen, which is very unfavourable; meta attack avoids that, so meta is the least-disfavoured path.",
        r: [["(a) Nitration then bromination, with correct reagents", 2], ["(b) Bromination then nitration, with correct reagents", 2], ["(c) Explains destabilized ortho/para intermediates", 1]] },
      { t: "sa", w: 12, q: "Give the major organic product(s): (a) ethyl benzoate + NaOH, H₂O, heat, then H₃O⁺; (b) benzoyl chloride + ethanol with pyridine; (c) acetic anhydride + excess NH₃; (d) ethyl acetate + excess CH₃MgBr, then H₃O⁺; (e) benzaldehyde + NaBH₄, then H₃O⁺.",
        s: "(a) Benzoic acid and ethanol (saponification, then protonation);  (b) Ethyl benzoate (pyridine takes up the HCl);  (c) Acetamide, plus ammonium acetate;  (d) 2-Methyl-2-propanol (tert-butyl alcohol) plus ethanol. Two Grignard additions: substitution gives acetone, which adds a second CH₃;  (e) Benzyl alcohol, C₆H₅CH₂OH.",
        r: [["(a) Benzoic acid and ethanol", 1], ["(b) Ethyl benzoate", 1], ["(c) Acetamide", 1], ["(d) tert-Butyl alcohol from two Grignard additions", 1], ["(e) Benzyl alcohol", 1]] },
      { t: "sa", w: 6, q: "2-Bromo-2-methylbutane is treated with: (a) methanol, warm, no added base; (b) NaOCH₂CH₃ in ethanol, heat; (c) KOC(CH₃)₃, heat. Give the main mechanism and major product for each. (d) Explain why (b) and (c) give different alkenes. (e) Explain why this substrate doesn’t react by SN2.",
        s: "(a) SN1 (with some E1): 2-methoxy-2-methylbutane is the main product;  (b) E2: 2-methyl-2-butene, the more substituted (Zaitsev) alkene;  (c) E2: 2-methyl-1-butene, the less substituted (Hofmann) alkene;  (d) Small ethoxide can reach the internal CH₂ hydrogens and forms the more stable alkene; bulky tert-butoxide removes the most accessible CH₃ hydrogens;  (e) The tertiary carbon is too crowded for backside attack.",
        r: [["(a) SN1 and 2-methoxy-2-methylbutane", 1], ["(b) E2 and 2-methyl-2-butene", 1], ["(c) E2 and 2-methyl-1-butene", 1], ["(d) Base size explains Zaitsev vs Hofmann", 1], ["(e) Steric hindrance blocks backside attack", 1]] }
    ]
  };

  /* ---------------- BIOC*2580 ---------------- */
  E["c2580-final"] = {
    kind: "final",
    weeks: [1, 12],
    minutes: 120,
    covers: "Everything in the course, weighted toward enzyme mechanisms and regulation, nucleic acids, membranes and transport, bioenergetics, glycolysis, the citric acid cycle, oxidative phosphorylation and fatty-acid breakdown (Fundamentals of Biochemistry Ch. 1–17 and 19). Use R = 8.314 J/mol·K and T = 310 K for body temperature.",
    questions: [
      { t: "mc", w: 1, q: "In the H₂PO₄⁻/HPO₄²⁻ buffer pair, which species is the conjugate base?",
        o: ["HPO₄²⁻", "H₂PO₄⁻", "H₃PO₄", "PO₄³⁻"], a: 0,
        e: "HPO₄²⁻ is H₂PO₄⁻ minus a proton, so it is the base of this pair." },
      { t: "mc", w: 2, q: "Which amino acid is most likely to be buried in the hydrophobic core of a water-soluble protein?",
        o: ["Lysine", "Glutamate", "Valine", "Serine"], a: 2,
        e: "Valine has a nonpolar side chain. Lysine and glutamate are charged and serine is polar, so they usually sit on the surface." },
      { t: "mc", w: 4, q: "Hemoglobin’s Hill coefficient is about 3. This means…",
        o: ["O₂ binding is positively cooperative", "each hemoglobin binds 3 O₂", "binding is non-cooperative", "hemoglobin has three subunits"], a: 0,
        e: "A Hill coefficient above 1 means positive cooperativity. Hemoglobin has four subunits and binds four O₂." },
      { t: "mc", w: 5, q: "Glycogen and amylose are mostly glucose units joined by…",
        o: ["β(1→4) bonds", "α(1→6) bonds only", "β(1→6) bonds", "α(1→4) bonds"], a: 3,
        e: "The main chains are α(1→4); glycogen also has α(1→6) branches. β(1→4) bonds make cellulose." },
      { t: "mc", w: 6, q: "On a Lineweaver–Burk plot, an inhibitor raises the slope and the y-intercept but leaves the x-intercept unchanged. It is…",
        o: ["a competitive inhibitor", "an uncompetitive inhibitor", "a substrate analogue that speeds up the enzyme", "a pure non-competitive inhibitor"], a: 3,
        e: "An unchanged x-intercept (−1/Km) means Km is unchanged; a higher y-intercept (1/Vmax) means Vmax fell. That is pure non-competitive inhibition." },
      { t: "mc", w: 7, q: "Which chymotrypsin residue acts as the nucleophile that attacks the peptide bond?",
        o: ["His57", "Asp102", "Ser195", "Gly193"], a: 2,
        e: "Ser195’s hydroxyl, activated by His57, attacks the carbonyl carbon. Gly193’s backbone N–H forms part of the oxyanion hole." },
      { t: "mc", w: 7, q: "Allosteric enzymes typically show…",
        o: ["sigmoidal v₀ versus [S] curves", "hyperbolic kinetics", "no response to effectors", "only competitive inhibition"], a: 0,
        e: "Cooperative subunits give S-shaped curves, and effectors shift them." },
      { t: "mc", w: 8, q: "The two strands of double-stranded DNA are held together mainly by…",
        o: ["covalent phosphodiester bonds between the strands", "hydrogen bonds between bases, plus base stacking", "disulfide bonds", "ionic bonds between the phosphates"], a: 1,
        e: "Phosphodiester bonds link nucleotides within one strand. The strands pair by base hydrogen bonds and are stabilized by stacking." },
      { t: "mc", w: 9, q: "Which molecule crosses a lipid bilayer most easily by simple diffusion?",
        o: ["Na⁺", "O₂", "Glucose", "ATP"], a: 1,
        e: "Small nonpolar molecules like O₂ dissolve through the bilayer. Ions and large polar molecules need proteins." },
      { t: "mc", w: 9, q: "The Na⁺/K⁺-ATPase is an example of…",
        o: ["simple diffusion", "facilitated diffusion", "secondary active transport", "primary active transport"], a: 3,
        e: "It uses ATP hydrolysis directly to pump ions against their gradients." },
      { t: "mc", w: 10, q: "Which enzyme catalyzes the main committed, regulated step of glycolysis?",
        o: ["Hexokinase", "Phosphofructokinase-1", "Aldolase", "Pyruvate kinase"], a: 1,
        e: "PFK-1 commits fructose 6-phosphate to glycolysis and is regulated by ATP, AMP, citrate and fructose 2,6-bisphosphate." },
      { t: "mc", w: 10, q: "How many ATP does glycolysis make by substrate-level phosphorylation per glucose, before subtracting the ATP it uses?",
        o: ["2", "6", "4", "36"], a: 2,
        e: "Two from phosphoglycerate kinase and two from pyruvate kinase: 4 gross, or 2 net after the 2 ATP used." },
      { t: "mc", w: 10, q: "In muscle working without enough O₂, pyruvate is converted to lactate in order to…",
        o: ["regenerate NAD⁺ so glycolysis can continue", "make extra ATP", "store carbon as fat", "produce CO₂"], a: 0,
        e: "Lactate dehydrogenase oxidizes NADH to NAD⁺, which glyceraldehyde 3-phosphate dehydrogenase needs. It makes no ATP itself." },
      { t: "mc", w: 11, q: "Which cofactor is NOT part of the pyruvate dehydrogenase complex?",
        o: ["Thiamine pyrophosphate", "Lipoate", "Biotin", "FAD"], a: 2,
        e: "Biotin is the cofactor of carboxylases such as pyruvate carboxylase. PDH uses TPP, lipoate, CoA, FAD and NAD⁺." },
      { t: "mc", w: 11, q: "Which citric acid cycle enzyme produces FADH₂?",
        o: ["Succinate dehydrogenase", "Malate dehydrogenase", "Isocitrate dehydrogenase", "Citrate synthase"], a: 0,
        e: "Succinate dehydrogenase oxidizes succinate to fumarate using FAD. The other two dehydrogenases use NAD⁺." },
      { t: "mc", w: 11, q: "In the first turn of the citric acid cycle, the two carbons released as CO₂ come from…",
        o: ["the acetyl group that just entered", "oxaloacetate", "GTP", "NADH"], a: 1,
        e: "Carbon-labelling experiments show both CO₂ in that turn come from the oxaloacetate part of citrate. The acetyl carbons leave in later turns." },
      { t: "mc", w: 12, q: "Which electron-transport complex does NOT pump protons?",
        o: ["Complex I", "Complex III", "Complex IV", "Complex II"], a: 3,
        e: "Complex II (succinate dehydrogenase) passes electrons to ubiquinone without pumping protons, which is why FADH₂ gives less ATP than NADH." },
      { t: "mc", w: 12, q: "Cyanide is lethal because it…",
        o: ["inhibits glycolysis", "uncouples the proton gradient", "inhibits ATP synthase directly", "blocks Complex IV, stopping electron flow to O₂"], a: 3,
        e: "Cyanide binds the heme iron in cytochrome c oxidase, so electron transport and ATP synthesis stop." },
      { t: "mc", w: 12, q: "An uncoupler such as 2,4-dinitrophenol causes…",
        o: ["more ATP and less heat", "electron transport to continue while ATP synthesis falls, releasing energy as heat", "electron transport to stop", "ATP synthase to spin faster"], a: 1,
        e: "It carries protons back across the membrane, bypassing ATP synthase. O₂ use continues or even rises, and the energy is lost as heat." },
      { t: "mc", w: 12, q: "How many acetyl-CoA does complete β-oxidation of stearate (18:0) produce?",
        o: ["8", "18", "9", "16"], a: 2,
        e: "18 carbons ÷ 2 = 9 acetyl-CoA, from 8 rounds of β-oxidation." },
      { t: "sa", w: 10, q: "(a) ATP hydrolysis has ΔG°′ = −30.5 kJ/mol. In a cell at 310 K with [ATP] = 3.0 mM, [ADP] = 1.0 mM and [Pi] = 5.0 mM, calculate the actual ΔG. (b) Why is it more negative than ΔG°′? (c) Phosphoenolpyruvate hydrolysis has ΔG°′ = −61.9 kJ/mol. Is PEP + ADP → pyruvate + ATP favourable under standard conditions? Show the calculation.",
        s: "(a) Q = [ADP][Pi]/[ATP] = (1.0 × 10⁻³)(5.0 × 10⁻³)/(3.0 × 10⁻³) = 1.67 × 10⁻³. RT ln Q = (8.314)(310)(−6.40) ≈ −16.5 kJ/mol, so ΔG = −30.5 − 16.5 ≈ −47 kJ/mol;  (b) Cells keep ATP far higher relative to ADP and Pi than equilibrium would allow (Q ≪ K), so hydrolysis is further from equilibrium and releases more free energy;  (c) Couple the reactions: −61.9 + 30.5 = −31.4 kJ/mol. Negative, so pyruvate kinase is strongly favourable.",
        r: [["(a) Correct Q expression", 1], ["(a) ΔG ≈ −47 kJ/mol", 1.5], ["(b) Concentrations held far from equilibrium", 1], ["(c) ΔG°′ = −31.4 kJ/mol, so favourable", 1.5]] },
      { t: "sa", w: 12, q: "Tally the ATP from completely oxidizing one glucose aerobically, using 2.5 ATP per NADH and 1.5 per FADH₂ (count cytosolic NADH as 2.5). Give the total for (a) glycolysis, (b) the pyruvate dehydrogenase step, (c) the citric acid cycle and (d) overall. (e) Which process makes most of the ATP, and how?",
        s: "(a) Glycolysis: 2 ATP (net) + 2 NADH (5 ATP) = 7;  (b) Pyruvate dehydrogenase: 2 NADH = 5;  (c) Citric acid cycle (2 turns): 6 NADH (15) + 2 FADH₂ (3) + 2 GTP (2) = 20;  (d) Total: 7 + 5 + 20 = 32 ATP;  (e) Oxidative phosphorylation: electron transport pumps protons, and ATP synthase uses the proton gradient to make ATP.",
        r: [["(a) 7", 1], ["(b) 5", 1], ["(c) 20", 1], ["(d) 32", 1], ["(e) Oxidative phosphorylation via the proton gradient and ATP synthase", 1]] },
      { t: "sa", w: 6, q: "Without inhibitor an enzyme has Km = 2.0 mM and Vmax = 120 µM/s. With 5.0 µM of an inhibitor, the apparent Km is 6.0 mM and Vmax is still 120 µM/s. (a) What type of inhibition is this? (b) Calculate Ki. (c) Calculate v₀ at [S] = 2.0 mM with and without the inhibitor. (d) How could the inhibition be overcome?",
        s: "(a) Competitive: Km rises while Vmax is unchanged;  (b) α = apparent Km / Km = 6.0/2.0 = 3.0 = 1 + [I]/Ki, so Ki = 5.0 µM ÷ 2.0 = 2.5 µM;  (c) Without: 120 × 2.0/(2.0 + 2.0) = 60 µM/s. With: 120 × 2.0/(6.0 + 2.0) = 30 µM/s;  (d) Raise the substrate concentration, which outcompetes the inhibitor for the active site.",
        r: [["(a) Competitive", 1], ["(b) Ki = 2.5 µM", 1.5], ["(c) 60 µM/s without inhibitor", 0.75], ["(c) 30 µM/s with inhibitor", 0.75], ["(d) Add more substrate", 1]] },
      { t: "sa", w: 12, q: "(a) Calculate ΔG for moving 1 mol of glucose into a cell where the glucose concentration is 5.0 mM inside and 0.50 mM outside, at 310 K. Can this happen passively? (b) Explain how the proton-motive force is made and used by ATP synthase. (c) Predict what happens to ATP synthesis and O₂ consumption if oligomycin blocks ATP synthase.",
        s: "(a) ΔG = RT ln(C_in/C_out) = (8.314)(310) ln(10) ≈ +5.9 kJ/mol. It is positive, so the move needs an energy source (active transport) and can’t happen passively;  (b) Complexes I, III and IV use energy from electron transfer to pump H⁺ from the matrix into the intermembrane space, creating a pH and charge gradient. H⁺ flows back through the F₀ part of ATP synthase, turning it, and the F₁ part uses that motion to make ATP from ADP and Pi;  (c) ATP synthesis stops. With no path back for protons, the gradient builds up until pumping can’t continue, so electron transport and O₂ consumption also slow and stop (they are tightly coupled).",
        r: [["(a) ΔG ≈ +5.9 kJ/mol", 1.5], ["(a) Not passive", 0.5], ["(b) Proton pumping creates the gradient, and flow through ATP synthase drives ATP synthesis", 1.5], ["(c) Both ATP synthesis and O₂ consumption stop, explained by coupling", 1.5]] }
    ]
  };

  /* ---------------- IPS*1500 ---------------- */
  E["c1500-final"] = {
    kind: "final",
    weeks: [1, 12],
    minutes: 120,
    covers: "Everything in the course, weighted toward friction and circular motion, integration, work and energy, momentum and collisions, rotation and angular momentum, special relativity and atomic structure (Calculus Vol. 1 Ch. 1–6; University Physics Vol. 1 Ch. 1–11; Vol. 3 Ch. 5 and 8). Use g = 9.8 m/s² and c = 3.0 × 10⁸ m/s.",
    questions: [
      { t: "mc", w: 1, q: "What is the angle between A = (1, 0, 0) and B = (1, 1, 0)?",
        o: ["30°", "45°", "60°", "90°"], a: 1,
        e: "cos θ = A·B/(|A||B|) = 1/(1 × √2), so θ = 45°." },
      { t: "mc", w: 3, q: "x(t) = 5 + 3t − t² (m). When is the object momentarily at rest?",
        o: ["3 s", "0 s", "5 s", "1.5 s"], a: 3,
        e: "v(t) = 3 − 2t = 0 at t = 1.5 s." },
      { t: "mc", w: 4, q: "d/dx [ln(sin x)] = ?",
        o: ["1/sin x", "cos x", "cot x", "tan x"], a: 2,
        e: "Chain rule: (1/sin x)(cos x) = cot x." },
      { t: "mc", w: 6, q: "Two forces act on a 2.0 kg object: 6.0 N east and 8.0 N north. What is the magnitude of its acceleration?",
        o: ["5.0 m/s²", "7.0 m/s²", "3.5 m/s²", "14 m/s²"], a: 0,
        e: "The net force is √(6² + 8²) = 10 N, so a = 10/2.0 = 5.0 m/s²." },
      { t: "mc", w: 7, q: "A block slides down a 20° ramp at constant velocity. What is the coefficient of kinetic friction?",
        o: ["0.34", "0.36", "0.94", "0.20"], a: 1,
        e: "Constant velocity means mg sin θ = μk mg cos θ, so μk = tan 20° ≈ 0.36. (0.34 is sin 20°.)" },
      { t: "mc", w: 8, q: "Evaluate ∫₀^π sin x dx.",
        o: ["0", "1", "2", "π"], a: 2,
        e: "[−cos x] from 0 to π = −cos π + cos 0 = 1 + 1 = 2." },
      { t: "mc", w: 8, q: "Find ∫ x·e^(x²) dx.",
        o: ["x²e^(x²) + C", "e^(x²) + C", "2e^(x²) + C", "½e^(x²) + C"], a: 3,
        e: "Let u = x², du = 2x dx: ∫ x·e^(x²) dx = ½∫eᵘ du = ½e^(x²) + C." },
      { t: "mc", w: 9, q: "A 0.50 kg ball is thrown straight up at 12 m/s. Ignoring air resistance, how high does it rise?",
        o: ["7.3 m", "3.7 m", "14.7 m", "1.2 m"], a: 0,
        e: "½mv² = mgh, so h = v²/(2g) = 144/19.6 ≈ 7.3 m. The mass doesn’t matter." },
      { t: "mc", w: 9, q: "A force F(x) = 3x² N acts on an object as it moves from x = 0 to x = 2 m. How much work does it do?",
        o: ["12 J", "6 J", "24 J", "8 J"], a: 3,
        e: "W = ∫₀² 3x² dx = [x³] from 0 to 2 = 8 J." },
      { t: "mc", w: 9, q: "A motor lifts a 50 kg crate 10 m at constant speed in 20 s. What is its power output?",
        o: ["490 W", "98 W", "245 W", "4900 W"], a: 2,
        e: "P = mgh/t = (50)(9.8)(10)/20 = 245 W." },
      { t: "mc", w: 10, q: "A 60 kg skater at rest pushes a 40 kg skater, who moves off at 3.0 m/s. How fast does the 60 kg skater move?",
        o: ["2.0 m/s in the opposite direction", "3.0 m/s in the opposite direction", "4.5 m/s in the opposite direction", "0 m/s"], a: 0,
        e: "Total momentum stays zero: 60v = 40 × 3.0, so v = 2.0 m/s the other way." },
      { t: "mc", w: 10, q: "In a perfectly inelastic collision…",
        o: ["kinetic energy is conserved", "the objects stick together and some kinetic energy is lost", "momentum is not conserved", "the objects bounce apart at the same speed"], a: 1,
        e: "Momentum is always conserved when no external force acts. “Perfectly inelastic” means the objects move off together, which loses the most kinetic energy allowed." },
      { t: "mc", w: 10, q: "What is the area of the region between y = x² and y = 4?",
        o: ["16/3", "32/3", "8", "16"], a: 1,
        e: "The curves meet at x = ±2: ∫ from −2 to 2 of (4 − x²) dx = [4x − x³/3] from −2 to 2 = 32/3." },
      { t: "mc", w: 11, q: "A wheel speeds up from 10 rad/s to 30 rad/s in 4.0 s. What is its angular acceleration?",
        o: ["10 rad/s²", "2.5 rad/s²", "7.5 rad/s²", "5.0 rad/s²"], a: 3,
        e: "α = Δω/Δt = 20 ÷ 4.0 = 5.0 rad/s²." },
      { t: "mc", w: 11, q: "A 2.0 kg hoop of radius 0.50 m rolls without slipping at 4.0 m/s. What is its total kinetic energy?",
        o: ["16 J", "24 J", "32 J", "64 J"], a: 2,
        e: "Translational ½Mv² = 16 J. Rotational ½Iω² = ½(MR²)(v/R)² = ½Mv² = 16 J. Total = 32 J." },
      { t: "mc", w: 11, q: "A merry-go-round (I = 500 kg·m²) spins at 1.0 rad/s. A 50 kg child steps onto it at the rim, 2.0 m from the axis. What is the new angular speed?",
        o: ["0.71 rad/s", "0.50 rad/s", "1.4 rad/s", "0.83 rad/s"], a: 0,
        e: "The new I = 500 + 50(2.0)² = 700 kg·m². Angular momentum is conserved: ω = 500 × 1.0/700 ≈ 0.71 rad/s." },
      { t: "mc", w: 12, q: "Muons made high in the atmosphere reach the ground despite their short lifetime. In the muon’s own frame, this is explained by…",
        o: ["time dilation of the muon’s clock", "length contraction of the atmosphere", "the muon moving faster than light", "the muon’s mass increasing"], a: 1,
        e: "In the muon’s frame its own clock runs normally, but the atmosphere rushing past is contracted, so there is less distance to cover. Earth observers explain the same result with time dilation." },
      { t: "mc", w: 12, q: "At what speed does the Lorentz factor γ equal 2?",
        o: ["0.50c", "0.71c", "0.87c", "0.99c"], a: 2,
        e: "1/√(1 − v²/c²) = 2, so 1 − v²/c² = ¼ and v = c√(3/4) ≈ 0.87c." },
      { t: "mc", w: 12, q: "A hydrogen atom’s electron drops from n = 3 to n = 2. What is the energy of the emitted photon?",
        o: ["12.1 eV", "3.40 eV", "10.2 eV", "1.89 eV"], a: 3,
        e: "ΔE = 13.6 eV × (1/2² − 1/3²) = 13.6 × 5/36 ≈ 1.89 eV (red light at 656 nm)." },
      { t: "mc", w: 12, q: "How many electrons can the n = 3 shell hold?",
        o: ["18", "8", "9", "32"], a: 0,
        e: "Capacity is 2n² = 18: 3s (2) + 3p (6) + 3d (10)." },
      { t: "sa", w: 9, q: "A 2.0 kg block starts from rest at the top of a frictionless ramp 3.0 m high, slides down, and then crosses a rough horizontal floor (μk = 0.25) until it stops. Find (a) its speed at the bottom of the ramp, (b) the friction force on the floor, (c) how far it slides on the floor and (d) the work done by friction.",
        s: "(a) mgh = ½mv², so v = √(2gh) = √(2 × 9.8 × 3.0) ≈ 7.7 m/s;  (b) f = μk·mg = 0.25 × 2.0 × 9.8 = 4.9 N;  (c) All 58.8 J of kinetic energy is removed by friction: f·d = 58.8 J, so d = 58.8 ÷ 4.9 = 12 m;  (d) W(friction) = −f·d = −58.8 J (it equals the loss of mechanical energy).",
        r: [["(a) v ≈ 7.7 m/s", 1.5], ["(b) f = 4.9 N", 1], ["(c) d = 12 m", 1.5], ["(d) W = −58.8 J, including the sign", 1]] },
      { t: "sa", w: 10, q: "A 0.20 kg puck moving east at 5.0 m/s hits a 0.30 kg puck at rest. Afterward, the 0.20 kg puck moves west at 1.0 m/s. (a) Find the velocity of the 0.30 kg puck. (b) Is the collision elastic? Show why. (c) Find the impulse on the 0.20 kg puck. (d) If the collision lasts 0.010 s, find the average force on the 0.20 kg puck.",
        s: "(a) Momentum (east positive): (0.20)(5.0) = (0.20)(−1.0) + (0.30)v, so 0.30v = 1.2 and v = 4.0 m/s east;  (b) KE before = ½(0.20)(5.0)² = 2.5 J. KE after = ½(0.20)(1.0)² + ½(0.30)(4.0)² = 0.1 + 2.4 = 2.5 J. Kinetic energy is conserved, so the collision is elastic;  (c) J = Δp = 0.20(−1.0 − 5.0) = −1.2 kg·m/s, which is 1.2 kg·m/s west;  (d) F = J/Δt = 1.2 ÷ 0.010 = 120 N west.",
        r: [["(a) 4.0 m/s east", 1.5], ["(b) Compares KE before and after (2.5 J each), so elastic", 1.5], ["(c) Impulse 1.2 kg·m/s west", 1], ["(d) Average force 120 N west", 1]] },
      { t: "sa", w: 11, q: "A solid-disk pulley (M = 4.0 kg, R = 0.20 m) turns freely on a fixed axle. A light string wrapped around it supports a 1.0 kg block, released from rest. (a) Write Newton’s second law for the block and for the pulley. (b) Find the block’s acceleration. (c) Find the tension in the string. (d) Find the block’s speed after it falls 1.0 m.",
        s: "(a) Block (down positive): mg − T = ma. Pulley: τ = TR = Iα, with I = ½MR² and α = a/R, so T = ½Ma;  (b) mg = (m + ½M)a, so 9.8 = (1.0 + 2.0)a and a ≈ 3.27 m/s²;  (c) T = ½Ma = 2.0 × 3.27 ≈ 6.5 N (check: 9.8 − 6.5 = 1.0 × 3.27);  (d) v = √(2ah) = √(2 × 3.27 × 1.0) ≈ 2.6 m/s.",
        r: [["(a) Both equations, using I = ½MR² and α = a/R", 1.5], ["(b) a ≈ 3.3 m/s²", 1.5], ["(c) T ≈ 6.5 N", 1], ["(d) v ≈ 2.6 m/s", 1]] },
      { t: "sa", w: 12, q: "A spaceship travels at 0.60c from Earth to a star 12 light-years away, as measured from Earth. (a) How long does the trip take in Earth’s frame? (b) Find γ. (c) How much time passes for the crew? (d) How far away is the star in the crew’s frame? (e) Show that (d) divided by the ship’s speed agrees with (c).",
        s: "(a) t = 12 ly ÷ 0.60c = 20 years;  (b) γ = 1/√(1 − 0.60²) = 1/0.80 = 1.25;  (c) Proper time for the crew: 20 ÷ 1.25 = 16 years;  (d) Contracted distance: 12 ÷ 1.25 = 9.6 ly;  (e) 9.6 ly ÷ 0.60c = 16 years, matching (c).",
        r: [["(a) 20 years", 1], ["(b) γ = 1.25", 1], ["(c) 16 years", 1], ["(d) 9.6 light-years", 1], ["(e) Shows 9.6 ÷ 0.60 = 16 years", 1]] }
    ]
  };
})(typeof self !== "undefined" ? self : this);
